- name: Create app directories
  ansible.builtin.file: # noqa risky-file-permissions
    path: "{{ item }}"
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: 0755
    state: directory
  loop: "{{ service_definitions | selectattr('volumes', 'defined') | map(attribute='name') | product([configuration_path]) | map('reverse') | map('join', '/') }}"
  when: not item is match('.*\.\w{2,4}$')

- name: Create Prometheus Config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ configuration_path }}/prometheus/{{ item.path | splitext | first }}"
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: 0755
  loop: "{{ lookup('community.general.filetree', 'templates/') }}"
  loop_control:
    label: "Files: {{ item.path }}"
  when: item.state == 'file'
  notify: Restart Prometheus
