---
- name: Install necessary packages
  ansible.builtin.apt:
    pkg: "{{ packages }}"
  become: true

- name: Create Git directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ clone_dir }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: '0755'

- name: Check if the directory exists
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/{{ clone_dir }}/webui-user.sh"
  register: repo_directory

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: "{{ automatic1111_git_url }}"
    dest: "{{ ansible_user_dir }}/{{ clone_dir }}"
  when: not repo_directory.stat.exists
