---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: tools
data:
  kubernetes.yaml: |
    ---
    mode: cluster
  settings.yaml: |
    ---
    title: Dashboard
    favicon: https://kubernetes.io/images/favicon.png
    theme: dark
    color: slate
    target: _self
    layout:
      Media Management:
        style: row
        columns: 4
      Tools:
        style: row
        columns: 2
      Observability:
        style: column
        columns: 1
      Media Automation:
        style: column
        columns: 1
      Security:
        style: row
        columns: 2
      Downloaders:
        style: row
        columns: 2
      Storage:
        style: row
        columns: 2
  bookmarks.yaml: |
    ---
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/chkpwd

    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  services.yaml: |
    ---
    - Infra:
      - OPNsense:
          href: https://opnsense.${LOCAL_DOMAIN}
          icon: opnsense.png
          description: Firewall and router
          widget:
            type: opnsense
            url: https://192.168.1.1
            username: ${SECRET_OPNSENSE_USERNAME}
            password: ${SECRET_OPNSENSE_PASSWORD}
  widgets.yaml: |
    ---
    - search:
        provider: [google, duckduckgo]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Chk's Lab!"
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "K3s"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: Control Plane
    - openmeteo:
        label: North Miami
        timezone: ${TZ}
        units: Imperial
        cache: 5
    - datetime:
      text_size: x1
      format:
        dateStyle: long
        timeStyle: short
  docker.yaml: ""
