---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: tools
data:
  kubernetes.yaml: |
    ---
    mode: cluster
  settings.yaml: |
    ---
    title: Dashboard
    favicon: https://kubernetes.io/images/favicon.png
    theme: dark
    color: sky
    target: _self
    layout:
      Media Management:
        style: row
        columns: 4
      Tools:
        style: row
        columns: 2
      Observability:
        style: column
        columns: 1
      Media Automation:
        style: column
        columns: 1
      Security:
        style: row
        columns: 2
      Downloaders:
        style: row
        columns: 2
      Storage:
        style: row
        columns: 2
  bookmarks.yaml: |
    ---
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/

    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  services.yaml: |
    ---
  widgets.yaml: |
    ---
    - search:
        provider: [google, duckduckgo]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Heya!"
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "K3s"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: Control Plane
    - openweathermap:
      label: Weather
      units: metric
      provider: openweathermap
      apiKey: "27e8c6700ff4e29b00929ca81650419c"
      cache: 5
    - datetime:
      text_size: x1
      format:
        dateStyle: long
        timeStyle: short
    # - unifi_console:
    #   url: https://unifi.host.or.ip:port
    #   username: user
    #   password: pass
    #   site: Site Name # optional
  docker.yaml: ""
