apiVersion: v1
kind: Secret
metadata:
    name: sops-secrets
    namespace: flux-system
stringData:
    PUBLIC_IP: ENC[AES256_GCM,data:ylCvFUX/NiOb4Kzf,iv:Eu2AlHMwaTdhHGoymGCG6fl3kcm0Z73Y6nnJtGFcWYE=,tag:584NkJ9ssmt9l0F2Rz9Zog==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:kHH3yOATHazUifTdYTNCb000pkzKVl7H94F6Wq3EmofQBq60DxbYxg==,iv:exSWkIvvnGyV1amuh5yPUIx8h/WhgnNwv+XZkhB5mvg=,tag:Xs1ahVfOsygY2Jt113DUFQ==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fpf6Wl2HnZbC9k2eUefW8X0t7XmW,iv:fdUsV5W7c9XeYEbqLNo//g6x3KxlxGuOWw07J01vHjc=,tag:agIvqO9M98Y+LSg8rFX4cg==,type:str]
    AWX_POSTGRES_PASSWORD: ENC[AES256_GCM,data:HupGWAj57keYlydKYtLkR+r0Zd1+5VGnp1VUPA==,iv:TIxW41zdl+QeW6vR5Eormm13X/ukVqSoPdNbsbSTJcU=,tag:ro8ozIn/NxVSoa7DIC182w==,type:str]
    AWX_REPLICATION_PASSWORD: ENC[AES256_GCM,data:IUJy9vDsJ003B9GCZQ+svGV9zhAC,iv:zNTvvlRgLe7I5IiCPWueHvf6ATx+LcKUH9z6ZDkcKxs=,tag:lgJXIEATogqnXXfzOko0XQ==,type:str]
    AWX_ADMIN_EMAIL: ENC[AES256_GCM,data:w2kq0/g8dbjXiopf0+GndWr659A6,iv:ErZlDKnt159TIlpoxir3uxY6S19xESUKhLtxEFUgyzI=,tag:oHJDF/uMo8fpAi6R9t2sQw==,type:str]
    AWX_ADMIN_PASSWORD: ENC[AES256_GCM,data:BnKJclRM/xLFfrzLYY+MvGlP2hn0,iv:sEyR3JuVkcvgmPjSUs36G1ekrvdM1BSoaAsrtlfc6Yk=,tag:/6dRW9IAXf6HBTGzO6V0ug==,type:str]
    ACTION_RUNNER_GIT_TOKEN: ENC[AES256_GCM,data:wd50p9P/SArg8gJcZKxDVhgsOCU/Zw9I4/YwqcyEafpe6RQqtwxTzw==,iv:kpooXx+DLJfkvGyOw8ZSzl7LOkUjKN9yDYvt2XnkO/g=,tag:GpQnynklQt1n/cGtQQHYIw==,type:str]
    API_KEY_SONARR: ENC[AES256_GCM,data:yTHbNy+KTAgfSnzYa5OW8CGZDZxbGnLBRgNloIzAPak=,iv:JLN0jYDaWQKtE1y6BSWlBe7JdOFhbArF5j2em1vWuIg=,tag:xgrIPlYtpkf+bpDvQutwKg==,type:str]
    API_KEY_RADARR: ENC[AES256_GCM,data:fNaLh5QJuZ2L36/NiIA8NABc/SCSSkN4jJ9pMoW+24Y=,iv:sex0aX6oNe2WhvbGsmQmUSRunNB2jTENItXc9E1rNOs=,tag:lYbzlKc2Vk6XSpqt0INhzw==,type:str]
    API_KEY_BAZARR: ENC[AES256_GCM,data:xil4EBvZCiMbvbWFk5Mp5Ne/VJmK8nr/MkMPSM2LVBQ=,iv:/C8Zid+Qigp3mMfdWpJpdDCcneZVr04uPQZLfgo3bRs=,tag:nsl/57hi5j+bbSNullK4cw==,type:str]
    API_KEY_PROWLARR: ENC[AES256_GCM,data:OiJ0r9l/n2anaYFHC2p91p73e2KM7b+uebtXnVgK7Kw=,iv:2bl13pOu8VJL4vR54kBC+ClpTlac7tEvcxHasCgz16s=,tag:dAXQRGFm0w2Amf31Jn9nGg==,type:str]
    API_KEY_SABNZBD: ENC[AES256_GCM,data:gkSXdRBDn58l3va7P5J0od1EaZ4mcAiFckl2mndK82I=,iv:GtDsYg7Vp2ZeJAsJAb7ptlnz3bCTA+D3u27K0R1l82g=,tag:Nho+lcClxU7BAjMvv+u6Jw==,type:str]
    API_KEY_NZBGEEK: ENC[AES256_GCM,data:3fiNn54RkoxgWFp0TeCcDyXfx3L3zeO7RrEe9UOMmp8=,iv:+Ps1lt6p9SyxUQ0XjcIzRfv1RxqTHPG5lC5Oxx9GP7g=,tag:4RkkxP1ZAYIWMzNzk527uQ==,type:str]
    API_KEY_IMMICH: null
    APP_PWD_KAVITA: ENC[AES256_GCM,data:vwFl8GKa23yKvyYqT+E4of+/SVRg,iv:6Uiqm5mdY2raYbzyjSzO2wUWN0vFE81HAHmfF7Bh6ag=,tag:3yP3rOX8iyrXc+NAgKN8ew==,type:str]
    APP_PWD_QBITTORRENT: ENC[AES256_GCM,data:ZSqvxr2/GnQTOPI=,iv:h74npEzMuobNJGMAkqP8stytvfhrDTiJAouZQ2gG01k=,tag:Ch2ixMFwquSI9AoCIdXdzA==,type:str]
    APP_PWD_MINIFLUX: ENC[AES256_GCM,data:Q4eLc8bFMz3zH0X2EddztlVX2CDFpLo=,iv:AELKBRCFaSzDRq8gv/vryFXGGTU1QWowIfb4q0FR/dU=,tag:gkVjJEwV9Y8I68S93y582Q==,type:str]
    DB_PWD_MINIFLUX: ENC[AES256_GCM,data:uGStW7bmKvno4awKkHhN7A2CUAFDKd0=,iv:FSpjIaRB5DLpEoM8ddeW8+HD75ighvLXxDZB9NH77xE=,tag:qK+dpmV1d4r/1isrC/WXSg==,type:str]
    DB_PWD_ZIPLINE: ENC[AES256_GCM,data:3MSFVBCn/XGd30AhsKFqJGOBhivnGEwUz8s=,iv:yS8ukjajl8GXOJx3FOOzEoGKd+sMp1A8xRQvMzd2AAE=,tag:bAm3D/z4oUW7K0x/JbNktA==,type:str]
    APP_KEY_OPNSENSE: ENC[AES256_GCM,data:l+kiNZOUDeON1SXudyV9jj87ckPPsWprZtZxncb+pjn/ZcxdhOQVoQSRJQDLqLhGpchWmBpD84HGz0z/75GaI42ub6lpNJG9CtDDHkWwr7s=,iv:1TGDb6d33tJnYPdDsIHPG1suuECN8cl98IGD0FAEaOU=,tag:ulScULDjwwH5mSkolIfI4w==,type:str]
    APP_SECRET_OPNSENSE: ENC[AES256_GCM,data:DyrHt0Z3XENNdlkrZDEvot21fODjJjWBiARY5I/irKEPUJdeo4T+zc/UIgTgEZEOTLiST5V/JRnKsvzQ4xemONdFP5u9B/yNmmYwq38PhC4=,iv:E3bAptuOnm2nQttjTZtx2Pf1Iug+HYBqA2YhZzCjcBk=,tag:bMfs/wfsmu1Nw7r7CzEDIQ==,type:str]
    APP_PWD_ADGUARD: ENC[AES256_GCM,data:qqLR1rSZFY//thox1FWP,iv:wmAuFP9FiEgBA6CqVKzd6rLAJGR0xkRjWLo8o+MtGPQ=,tag:gix95aLeb7WLZpt12oSFbQ==,type:str]
    APP_PWD_UNIFI: ENC[AES256_GCM,data:+wIOSUkVQOU+Te8Z90Fr6R98ezJYr+w=,iv:N20RwArgvRNGetJVau0jmI1PycNOYAYzXAYrhnaOQqk=,tag:zI7//LTK5dD48GF48tlafw==,type:str]
    APP_PWD_AUTHENTIK: ENC[AES256_GCM,data:A21ik5SjGaF2+RnoE/4mI7zxKhK/fsdB1+33nnbAnnD85IUO+/i9OjQetOQR3H/xeWE=,iv:x78vLr7d+Vj+VNBSIyHJgqX0A2Ze5tfD7VzcBQcfxfg=,tag:LR3ZE/PqD1qnY26xfJNI/Q==,type:str]
    DB_PWD_AUTHENTIK: ENC[AES256_GCM,data:2BFK7CrSB/XHq+S7LhArlb5noufkWU4mgAiP5XE2Zuv6Ji0zFORVBsFx1uTR85tV,iv:LXQgUMyUpgbpTJiS8U7RgpfjKqA0yDJWzVtQGiCkFQ0=,tag:hjD2uHWeFuwfjlAsFplMJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R21KT3JqdklkeVF6cytm
            QzRFMUx1T1c5ZlBDajF2Tzl5Rkd6cmdvSlNFCkhVL2lPTjNqbFV6TklnamNvRU1I
            RGJmeC9RL05idUV5OU40dEpXcndSMEEKLS0tIHVKZXVsRis0RFd2UFlXWTIzZm1x
            WU5xRVZaVG5ONVBIYTU0RU1MZktkQm8KDlwe/HtdV+pHgpZkxigRhgTboP37/rE8
            QBDE5MEFMGvTFAxGwfQNDBy636aQCppuz1g9kZ7RSVV22IETeW4oaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T17:15:41Z"
    mac: ENC[AES256_GCM,data:BbE8ANpekOMgJ8AV8tUwnpYRyiUYxuQdsvQ+2qW389ZoCh0bZZFdlUeU60/wcZiujZDlo6PTLdcoVPIsEjwpiTYs7gx7pOhaaWbywHIWXXdp7B8mOwyb9QzUNuCU/9LI7kd5ZziQuADBizsQwpVVAFujiSHf6JpMogxVJ4VLc9M=,iv:yFpfrlq/uqWus3ELKeVSs3L1PX5SzCtOjlyV8IpD+VA=,tag:rvklf2ymUufgZMmRdvnNYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
