apiVersion: v1
kind: ConfigMap
metadata:
  name: global-vars
  namespace: flux-system
data:
  LOCAL_DOMAIN: local.chkpwd.com
  EXTERNAL_DOMAIN: chkpwd.com
  K8S_GATEWAY_DOMAIN: k8s.chkpwd.com
  CLUSTER_DOMAIN: svc.cluster.local
  KUBE_VIP_ADDRESS: 172.16.16.13
  NGINX_LB_INT_ADDRESS: 172.16.16.30
  NGINX_LB_EXT_ADDRESS: 172.16.16.31
  K8S_GATEWAY_LB_ADDRESS: 172.16.16.32
  UNIFI_LB_ADDRESS: 172.16.16.33
  JELLYFIN_LB_ADDRESS: 172.16.16.34
  TZ: "America/New_York"
  CP_NODES: "172.16.16.10,172.16.16.11,172.16.16.12"
