# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: clusters
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   dependsOn:
#     - name: core
#   path: ./kubernetes/clusters
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: chkpwd-ops
#   postBuild:
#     substituteFrom:
#       - kind: ConfigMap
#         name: global-vars
