apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/core/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
