---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app atuin
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/ellie/atuin
      tag: 15.0.0

    command: ["atuin", "server", "start"]

    env:
      TZ: ${TZ}
      ATUIN_HOST: "0.0.0.0"
      ATUIN_PORT: &port "8888"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI:
        valueFrom:
          secretKeyRef:
            name: atuin-pguser-atuin
            key: uri

    service:
      main: 
        ports: 
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 10m
        memory: 50M
      limits:
        memory: 50M
