---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-db-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
