apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:W0reRcgmQz7OFdvPAcSnKUocJDFAvlzc+AX3IlzTSAXb2h4o7H8rko6WdCJd8zoynmzSNYPj4GKFmuFjC/gVpPgrL4xCTvSACuDut3HHrbSKbyK/bDq4U2Q=,iv:w7Buuz6ezdB6Oc5hFHsU4o+9hNojGD6crilC9Z1IV14=,tag:LeOQ9A5zizIXM4N5Fs3oSg==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:f3yVrsikqRA=,iv:kb22lmDndkD6LkYNcZMK0a9ffR8oTApjDRz9vxHrR9U=,tag:R33x7seRSodAy42iI9HZRg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:8yNbIPxTwLZvvo1dT1i2Zb6mSQ==,iv:xnc4GxznXaKq/M4RoVkN7QMgTVOaB718ohWxCbnaGEI=,tag:ab35zzajjZVUM4edxI0UZw==,type:str]
    #ENC[AES256_GCM,data:aEdzwXujlgD9iHS4tzY+m9o4Ft/pANGZfXZFB/s4P9TV2hMV5HPEFu3+W7g=,iv:E2iQ/nSnNhq4igZJbYvH84sga19qz4w+zwMqdWqLBZM=,tag:wEB42WbBN+4x1vMC621Ang==,type:comment]
    #ENC[AES256_GCM,data:5GVHdmGrfxUg784TDi11YWifTrWmO63g/omdb5g/6/dSciqWzTDGae14oQM0T4teQ4B+uA==,iv:3Vg6TRPmmzbonKG5+/aTaNmuTKQGjjrUoOlHotLHcmo=,tag:jmiRow1OoIwUSkt+sK09YA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTzB4bjBuSFhyY1dHOXVk
            MHhoQmVCSENMaEl3UVowZGxmQzR5Z1I3eVdVCnZ6ZzJ3ckJqN1B3ZmxSU2hoTXJE
            SHpnYjNNT0ZBamt4Q0NxQk1jZVRnRWcKLS0tIEtwSWg3TkRpYm16ai9tcmd1Wi9C
            Wm9qdG9DdDV5Mnc4WU02QmZ2T0FvRWcK3yMylRzDrNSgZ/KSsFOXJk58d+P/M/BS
            JV6T2nvUPUUyF5T4Y0Wj9JJuIMz9zlJHE9X3i6gjIrVqMBky3z3CEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T23:18:26Z"
    mac: ENC[AES256_GCM,data:vmicN7u5E2KATWVIAsie0PvOjHzxb8LirfbJiVB2PwnnjOMRzA/B2GFOTiaty+yIgd+LoIsNwprYYKJKMSWpV/SHWHv1zL3z3bm1B0v/+OzYqgEjHp/6cD9hjzLfLAuctxPFyP5xoK8wwuK8gD9DqSCOwOYLs0cREUf1hAU1Bmc=,iv:7m5mEGArSiw52rKbEOGrXZQK0Oa6ourQQR112XvDw44=,tag:d6E+CLKqRPTEK320eaVwMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
