apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: tools
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:f3yVrsikqRA=,iv:kb22lmDndkD6LkYNcZMK0a9ffR8oTApjDRz9vxHrR9U=,tag:R33x7seRSodAy42iI9HZRg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:8yNbIPxTwLZvvo1dT1i2Zb6mSQ==,iv:xnc4GxznXaKq/M4RoVkN7QMgTVOaB718ohWxCbnaGEI=,tag:ab35zzajjZVUM4edxI0UZw==,type:str]
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:21SxGwph0n8=,iv:X8dBaqMkd9zC8QwUv3ox+Vf7gUfH1yNMdN77t3Xcdw4=,tag:HOqFjqhs69mX6pG+iLRDhA==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:MCncVlj0olEvmmevfcgZkh5TvKutWHIdtXTtQp9/rGGu22ozLGCA38CER+amACbj+Ud4q/zkUBAuteiOv9D+OA==,iv:03ivFqicP18xjTiimzSZnCsubMnpGRGg/fSqm+uOzv0=,tag:6Hnk8OefFFKVPimZ9GYIyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTzB4bjBuSFhyY1dHOXVk
            MHhoQmVCSENMaEl3UVowZGxmQzR5Z1I3eVdVCnZ6ZzJ3ckJqN1B3ZmxSU2hoTXJE
            SHpnYjNNT0ZBamt4Q0NxQk1jZVRnRWcKLS0tIEtwSWg3TkRpYm16ai9tcmd1Wi9C
            Wm9qdG9DdDV5Mnc4WU02QmZ2T0FvRWcK3yMylRzDrNSgZ/KSsFOXJk58d+P/M/BS
            JV6T2nvUPUUyF5T4Y0Wj9JJuIMz9zlJHE9X3i6gjIrVqMBky3z3CEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-25T19:32:15Z"
    mac: ENC[AES256_GCM,data:5qpnwcxfQphwHOm2DdzK0hcxni80rMMcguh/7H8kEZ8sr6eqI0ffzU0EDVh9+3eoOeCSno5So+HE2EAclR122tF3fXue7a+HdP9yIsQCReeW+lz6GQuDW1R4SVUWPgVoSpO2UQhgK61ijhyCYurEhLr3RWV3z13sBfhpomLSZk4=,iv:K5TNjBAPKVTg0g1cRJbz8LzLGpF+vr8lZc7DzL80dmc=,tag:8qQCmPbTiFUvEm+0/qrWrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
