apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: tools
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Seqzqd3nvnt7kUaLGZuSLZzwtL1Gu0dpxKZDAL1mNM9zPFaSRoSUJ9HggHI1yENb5nHto9qWFn1RpVzOwyxLutkYcmvK/Sz40Vs9McKYSsHwwskqcmBzSotNnfIUNr7jjMvoh9Rf31SI2cqwQquJE0jzcaQ=,iv:2pqQo5y20C4K5SuU0z+qezIglIjOvNpULi+okZYzu70=,tag:fxtfSJjoaDC1ImoYQGDjog==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:f3yVrsikqRA=,iv:kb22lmDndkD6LkYNcZMK0a9ffR8oTApjDRz9vxHrR9U=,tag:R33x7seRSodAy42iI9HZRg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:8yNbIPxTwLZvvo1dT1i2Zb6mSQ==,iv:xnc4GxznXaKq/M4RoVkN7QMgTVOaB718ohWxCbnaGEI=,tag:ab35zzajjZVUM4edxI0UZw==,type:str]
    POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:iXqWa4iCJCSi/yY3VualLr5wDPh5r4JT4g==,iv:1Kt1T/ES7aK24jsAdpt+y+H9n2MNwfSNWh3QspI0G/k=,tag:HaRRrdZTCzsiI8JfSys75A==,type:str]
    #ENC[AES256_GCM,data:aEdzwXujlgD9iHS4tzY+m9o4Ft/pANGZfXZFB/s4P9TV2hMV5HPEFu3+W7g=,iv:E2iQ/nSnNhq4igZJbYvH84sga19qz4w+zwMqdWqLBZM=,tag:wEB42WbBN+4x1vMC621Ang==,type:comment]
    #ENC[AES256_GCM,data:5GVHdmGrfxUg784TDi11YWifTrWmO63g/omdb5g/6/dSciqWzTDGae14oQM0T4teQ4B+uA==,iv:3Vg6TRPmmzbonKG5+/aTaNmuTKQGjjrUoOlHotLHcmo=,tag:jmiRow1OoIwUSkt+sK09YA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTzB4bjBuSFhyY1dHOXVk
            MHhoQmVCSENMaEl3UVowZGxmQzR5Z1I3eVdVCnZ6ZzJ3ckJqN1B3ZmxSU2hoTXJE
            SHpnYjNNT0ZBamt4Q0NxQk1jZVRnRWcKLS0tIEtwSWg3TkRpYm16ai9tcmd1Wi9C
            Wm9qdG9DdDV5Mnc4WU02QmZ2T0FvRWcK3yMylRzDrNSgZ/KSsFOXJk58d+P/M/BS
            JV6T2nvUPUUyF5T4Y0Wj9JJuIMz9zlJHE9X3i6gjIrVqMBky3z3CEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T00:45:09Z"
    mac: ENC[AES256_GCM,data:FqjIuyIf5jiECrGvcDidmgPgziJbk/958du1cYFVr7iCTzz4L4NxlGnz8r6ftclW32UtRQUews5pbMmQY42v+WrIj6/PJLsf9QBIu8I5dQsYvhkQAPWpeSpjCl2HJgslilGJ8Q3ROGnzwp2gsgaM+gxr5c2pFG/rTQk4kxxZc4Y=,iv:R/pbdhfxY4CQa60HyQ89jlq8hcVJfFSVN77D1/mxUKg=,tag:RO01Ei/lRr3Z8A5Gm0ihKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
