apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: tools
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:MMAEggrXhWr8MiM23WfSiiLoZ2zefuSCAmhP4pl3RuZ9S9dU6xvUzTjDQosq0tE38biZZQDJvlPDNoxBxU7lTCjmlFdsjqiO2qpSUaCNtUxElKdqk1lfUM3GRMq37TIcomJB5fSMCrYrII7cPR1L2sQ2AA==,iv:Wq0Sn21t5k8fff/sIk8jtUTCXR1PzXHhB5XViAXb0KA=,tag:+Nb0iX7RivZbXZAtOGiYCA==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:f3yVrsikqRA=,iv:kb22lmDndkD6LkYNcZMK0a9ffR8oTApjDRz9vxHrR9U=,tag:R33x7seRSodAy42iI9HZRg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:8yNbIPxTwLZvvo1dT1i2Zb6mSQ==,iv:xnc4GxznXaKq/M4RoVkN7QMgTVOaB718ohWxCbnaGEI=,tag:ab35zzajjZVUM4edxI0UZw==,type:str]
    POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:iXqWa4iCJCSi/yY3VualLr5wDPh5r4JT4g==,iv:1Kt1T/ES7aK24jsAdpt+y+H9n2MNwfSNWh3QspI0G/k=,tag:HaRRrdZTCzsiI8JfSys75A==,type:str]
    #ENC[AES256_GCM,data:aEdzwXujlgD9iHS4tzY+m9o4Ft/pANGZfXZFB/s4P9TV2hMV5HPEFu3+W7g=,iv:E2iQ/nSnNhq4igZJbYvH84sga19qz4w+zwMqdWqLBZM=,tag:wEB42WbBN+4x1vMC621Ang==,type:comment]
    #ENC[AES256_GCM,data:5GVHdmGrfxUg784TDi11YWifTrWmO63g/omdb5g/6/dSciqWzTDGae14oQM0T4teQ4B+uA==,iv:3Vg6TRPmmzbonKG5+/aTaNmuTKQGjjrUoOlHotLHcmo=,tag:jmiRow1OoIwUSkt+sK09YA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTzB4bjBuSFhyY1dHOXVk
            MHhoQmVCSENMaEl3UVowZGxmQzR5Z1I3eVdVCnZ6ZzJ3ckJqN1B3ZmxSU2hoTXJE
            SHpnYjNNT0ZBamt4Q0NxQk1jZVRnRWcKLS0tIEtwSWg3TkRpYm16ai9tcmd1Wi9C
            Wm9qdG9DdDV5Mnc4WU02QmZ2T0FvRWcK3yMylRzDrNSgZ/KSsFOXJk58d+P/M/BS
            JV6T2nvUPUUyF5T4Y0Wj9JJuIMz9zlJHE9X3i6gjIrVqMBky3z3CEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T01:44:19Z"
    mac: ENC[AES256_GCM,data:8h124aD0WgMrqznNPM605ieP3M8Fqio8xzjQ+F9Ted13uLZzR1+dJleAHed3rNezodsTIfjDUO3iiD0O4tomXdjGBxMzG3RMTGRuhJgU4TBquAi4fz9et+GJaq+PqZ7nKfwL2xOvKkcOaiCB10Dqdjsf7OrhCxFZoE60HRIMmDs=,iv:+7UCH7wbiAXp66K5p6RRVmLi2a0Q7TjXlcWn4Iutowk=,tag:qCCgT0ostsBrudjhR8ayzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
