apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: tools
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:f3yVrsikqRA=,iv:kb22lmDndkD6LkYNcZMK0a9ffR8oTApjDRz9vxHrR9U=,tag:R33x7seRSodAy42iI9HZRg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:8yNbIPxTwLZvvo1dT1i2Zb6mSQ==,iv:xnc4GxznXaKq/M4RoVkN7QMgTVOaB718ohWxCbnaGEI=,tag:ab35zzajjZVUM4edxI0UZw==,type:str]
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:21SxGwph0n8=,iv:X8dBaqMkd9zC8QwUv3ox+Vf7gUfH1yNMdN77t3Xcdw4=,tag:HOqFjqhs69mX6pG+iLRDhA==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:lLD+Ij5Fo+4=,iv:DhJmyJWP+NbJEDNIF2vllHVtkWHr0EdIF86NBf3yDwo=,tag:jQLkDyInPLMlbCGZ1mDPhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTzB4bjBuSFhyY1dHOXVk
            MHhoQmVCSENMaEl3UVowZGxmQzR5Z1I3eVdVCnZ6ZzJ3ckJqN1B3ZmxSU2hoTXJE
            SHpnYjNNT0ZBamt4Q0NxQk1jZVRnRWcKLS0tIEtwSWg3TkRpYm16ai9tcmd1Wi9C
            Wm9qdG9DdDV5Mnc4WU02QmZ2T0FvRWcK3yMylRzDrNSgZ/KSsFOXJk58d+P/M/BS
            JV6T2nvUPUUyF5T4Y0Wj9JJuIMz9zlJHE9X3i6gjIrVqMBky3z3CEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T12:30:51Z"
    mac: ENC[AES256_GCM,data:/Jl3Z1TOuqf5eYbmG3RRW6bU2VgiWIVLgaD7MnlwjGX8hu/Mr7kGW5adzwnRHM0wVpH3n0jLqiS6QPUbmM0sJv569sua6N1Pv59vT14GFmS0cfWe/UrGNPGTaPCgRpiC7tIQYOLMT6E3lw2av2AxUVXLt8tC5SAwTXUWg3w550M=,iv:sP17QWPvo58ifZIJ4Ohnc0XYLaX1D8uzopcKpDG6Dr4=,tag:3dW2D2fG5fBk4hN4knS4Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
