apiVersion: v1
kind: Secret
metadata:
    name: jitsi-meet-secrets
stringData:
    password: ENC[AES256_GCM,data:4VA22OO4rsmWTuYTUq4hvhg78ec=,iv:Sh2IltG5mX2AK15F9Pndov3QaKhUqrxAnAS0/nF9i0Q=,tag:Z+bo/z+eHNOMHCEH1o6ZHg==,type:str]
    componentPasscode: ENC[AES256_GCM,data:OljHWcEnjLVZDuGPE5ayUlWyNqZnXlRDyebe4zUT1AXyzw==,iv:qvYzzYYUGhSpynAb6M9d8zOcsdEZCTqR30lgC9tpkCw=,tag:PsPv1kcR1HncBQ8Bg6BECg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eEJPNmcwQ2Q2UlE0eC9T
            M0NoWkRGUmJUNkQvUUdva1lxUERPN200QWdvCkc4UW5id1ZyVFJwWEc4SllYOU01
            WTZqSWRLSXBsb2x4bXFXdDRIS0VkREkKLS0tIGw2UTNjS0haQVhSZnRJN3BrS3Vr
            V2Y0eSszYm1HWHZ2MXdoTWdadjBUOU0K71pUEVGW8A+S/OcggTPFeil38AmOAKl+
            PvbO2iRMJsOqRczv7Rxo2HhlLzRzhruf0nKUMX4z8bMyZSiLmVbP5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-22T01:37:54Z"
    mac: ENC[AES256_GCM,data:ahkYrBmLkn6B40YgdXeZGfdh0WR77e/1ZD4dqpslTl8BiSUaY2Mp+8n7J9x+G6DPg33IdUDIcRPttrqbui4JFWVKzqgcQRCJBL2xg78wQSArlYaK+ISH/0YIQjkuUj1X8zFxrv50H+oYknNqkoxQeEtPLqu1SR6+g2mKMtLPIKc=,iv:KRlBDOiTbWbmmOFYzlrm2fnSpmIeIQOZjisUtHjD+5g=,tag:PBtMYRUl7dhpSbtKUyThlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
