apiVersion: v1
kind: Secret
metadata:
    name: shlink-secrets
    namespace: tools
stringData:
    GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:04x9HfigaQLJrow0tKjuTwSgEsTnLhiv5/mkvOr9oVj1pBMv+d8bjA==,iv:lXonDmhFnSFPLDwjwob9Wr/su3jKLw3im61ut3oKZeQ=,tag:asSgl4uWeYyixvWsd55Avw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QUp2MWl2VDl0YUFTNGx2
            QTlYRlV6L3lLRnY3UHBTMUhRam1zdm5tTVNrCjJ6MlZJM3duTnlxRWRtaXNHWTIw
            T0ppTEhaSVNTcGJNaUZyM3FhUVhqL3cKLS0tIDVrR0dibzg0ZnNuY0I3alpEYnlz
            ekNJdTROL3Vzd09xWW5GNDdxOWM5RW8KC486z4ercDOc6ozSgJmLgiigyXqW2UpS
            1ll+hz0kwGaZK5wxVjGBuAt5HnrfVX9txhZO6i5VS3WecsRZ1h2i6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T00:02:40Z"
    mac: ENC[AES256_GCM,data:v+bsnJPpb7NRwO5iJoL/NzcK7cZSNHoEgb3aVWbK9pp/XOr5l8M2SWMdxdFxndb65fwYpnILPab7oI8tOqmI8dypCscDS4QEVnXiGHBcCbbUf54K7NGvYkGyCoxHlOJbLqCJw8Eu+ZMqOVuTaT6JQ9DW32u5WJ+rtg0nN2pX2aU=,iv:N4WMyttzQtyVBe/7k2aFj4ozpiisvI0MTqLWm4QLFLw=,tag:U4jSDmCgPx7UgSkw+m7JAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
