---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools-zipline
  namespace: flux-system
spec:
  dependsOn:
    - name: tools-zipline-config
  path: ./kubernetes/apps/tools/multi-app/zipline
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools-zipline-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/tools/zipline/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
