---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 7.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.10.0
      pullPolicy: Always

    controller:
      resources:
        requests:
          cpu: 15m
          memory: 94M
        limits:
          memory: 270M

    dashboard:
      enabled: true
      replicaCount: 1

      service:
        type: ClusterIP
        port: 80
        annotations: {}

      resources:
        requests:
          cpu: 15m
          memory: 64Mi
        limits:
          memory: 105M

      ingress:
        enabled: true
        ingressClassName: int-ingress
        hosts:
          - host: &host "goldilocks.${K8S_GATEWAY_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - secretName: chkpwd-cert-production
            hosts:
              - *host