---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 7.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    fullnameOverride: *app

    vpa:
      enabled: false
      updater:
        enabled: false

    metrics-server:
      enabled: false
      apiService:
        create: true

    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.10.1
      pullPolicy: Always

    controller:
      enabled: true

      rbac:
        create: true

      serviceAccount:
        create: true

      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10324
        capabilities:
          drop:
            - ALL

      resources:
        requests:
          cpu: 15m
          memory: 94M
        limits:
          memory: 270M

    dashboard:
      enabled: true
      replicaCount: 1

      rbac:
        create: true
        enableArgoproj: true

      serviceAccount:
        create: true

      service:
        type: ClusterIP
        port: 80

      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10324
        capabilities:
          drop:
            - ALL

      resources:
        requests:
          cpu: 15m
          memory: 64Mi
        limits:
          memory: 105M

      ingress:
        enabled: true
        ingressClassName: int-ingress
        hosts:
          - host: &host "goldilocks.${K8S_GATEWAY_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - secretName: chkpwd-cert-production
            hosts:
              - *host
