---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: awx-operator
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: awx-chart
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    fullnameOverride: &app awx
    AWX:
      enabled: true
      name: *app
      spec:
        admin_user: admin
        admin_email: ${AWX_ADMIN_EMAIL}
        admin_password_secret: ${AWX_ADMIN_PASSWORD}
