---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app twingate-connector
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: connector
      version: 0.1.21
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    image:
      repository: twingate/connector
      tag: 1.59.0

    hostNetwork: false  # To enable hostnetwork for pod

    env: {}

    icmpSupport:
      enabled: false

    connector:
      logLevel: "error"
      network: "chkpwd"
      existingSecret: "twingate-connector"
      dnsServer: 172.16.16.1


    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    resources:
      requests:
        cpu: 50m
        memory: 200M
      limits:
        memory: 300M
