---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.30
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    adminUser:
      create: true
      createSecret: false
      username: admin

    ingress:
      enabled: true
      className: int-ingress
      hosts:
        - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    networkPolicy:
      create: false

    metrics:
      enabled: true

    rbac:
      create: true
      impersonationResourceNames: ["admin"]

  valuesFrom:
    - kind: Secret
      name: weave-gitops-secrets
      valuesKey: adminPassword
      targetPath: adminUser.passwordHash