---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development-tf-controller
  namespace: flux-system
spec:
  dependsOn:
  - name: development-tf-controller-config
  path: ./kubernetes/apps/development/tf-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development-tf-controller-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/development/tf-controller/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
