---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-web
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  dependsOn:
    - name: immich-server

  values:
    global:
      fullnameOverride: *app

    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-web
      tag: v1.74.0
    args: ["./entrypoint.sh"]
    command: /bin/sh

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Immich
          gethomepage.dev/group: Collaboration
          gethomepage.dev/icon: immich
          gethomepage.dev/description: "Self-Hosted Photo App"
          gethomepage.dev/widget.type: immich
          gethomepage.dev/widget.url: "http://immich-web.tools.${CLUSTER_DOMAIN}:3000"
          gethomepage.dev/widget.key: ${API_KEY_IMMICH}
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: rewrite /api/(.*) /$1 break;
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /api
                pathType: Prefix
                service:
                  name: immich-server
                  port: 3001
        tls:
          - hosts:
              - *host

    persistence:
      library:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/images
        mountPath: /usr/src/app/upload

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-cm

    resources:
      requests:
        cpu: 5m
        memory: 64M
      limits:
        memory: 64M
