---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: development
spec:
  ingress_type: ingress
  ingress_class_name: int-ingress
  hostname: &host "awx.${LOCAL_DOMAIN}"
  ingress_annotations: |
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: AWX
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: awx
    gethomepage.dev/description: "Ansible Automation Platform"
    gethomepage.dev/href: "https://awx.${LOCAL_DOMAIN}"
  ingress_path: '/'
  ingress_path_type: 'Prefix'
  ingress_tls_secret: *host
