---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 1.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    image:
      repository: ghcr.io/benphelps/homepage
      tag: v0.6.21

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: *app

    # This enables the service account to access the necessary resources
    enableRbac: true

    env:
      TZ: "${TZ}"
      PORT: &port 3000

    service:
      main:
        ports:
          http:
            port: *port

    hostname: *app

    ingress:
      main:
        enabled: true
        ingressClassName: int-ingress
        hosts:
          - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    config:
      useExistingConfigMap: *app
    logs:
      enabled: true
      type: emptyDir
      mountPath: /app/config/logs

    resources:
      requests:
        cpu: 35m
        memory: 150Mi
      limits:
        memory: 225Mi
