---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      interval: 30m
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system

  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    fullnameOverride: *app

    crd:
      create: true

    image:
      repository: registry.k8s.io/external-dns/external-dns
      tag: v0.13.5
      pullPolicy: IfNotPresent

    provider: cloudflare

    cloudflare:
      email: ${CLOUDFLARE_EMAIL}

    podSecurityContext:
      fsGroup: 65534

    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]

    env:
      - name: CF_API_TOKEN
        value: ${CLOUDFLARE_API_TOKEN}

    extraArgs:
      - --ingress-class=ext-ingress
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint

    policy: sync

    sources: ["crd", "ingress"]
    
    txtPrefix: k3s.
    txtOwnerId: default

    logLevel: info
    logFormat: text
    
    domainFilters: [ "${EXTERNAL_DOMAIN}" ]

    serviceMonitor:
      enabled: true
    
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 125Mi
