---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app plex
  namespace: networking
spec:
  ingressClassName: ext-ingress
  annotations:
    external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
  rules:
    - host: &host plex.${EXTERNAL_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 32400
  tls:
    - hosts:
        - *host