---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.18.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    crds:
      create: true