---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app overseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      nameOverride: *app

    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.33.0

    env:
      TZ: "America/New_York"
      LOG_LEVEL: info
      PORT: &port 5055

    hostname: *app

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: User requests management
          gethomepage.dev/group: Media Automation
          gethomepage.dev/icon: overseerr.png
          gethomepage.dev/name: Overseerr
          gethomepage.dev/widget.type: "overseerr"
          gethomepage.dev/widget.url: "http://overseerr.media.svc.cluster.local"
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [65534]

    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 300Mi
