---
zsh_dynamic_plugins:
  - git
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - sudo
  - z
  - terraform
  - docker
  - docker-compose
  - aws

container_path: /data
arr_uid: "1000"
arr_gid: "1000"

extra_packages:
  - git
  - tmux

common_env: &common_env
  TZ: America/New_York
  PUID: "{{ arr_uid }}"
  PGID: "{{ arr_gid }}"
