---
common_user: chkpwd
ansible_user: chkpwd

service_definitions:
  - name: gravity
    image: ghcr.io/beryju/gravity:v0.6.13
    network_mode: host
    env:
      BOOTSTRAP_ROLES: dns;api;etcd;discovery;backup;monitoring;tsdb
      DATA_PATH: /data
      LOG_LEVEL: info
      ADMIN_PASSWORD: "{{ GRAVITY_ADMIN_PASSWORD }}"
      ADMIN_TOKEN: "{{ GRAVITY_TOKEN }}"
      LISTEN_ONLY: "true"
    volumes:
      - "{{ configuration_path }}/gravity:/data"
    log_driver: json-file
    log_options:
      max-size: "10m"
      max-file: "3"

  - name: prometheus
    image: prom/prometheus:v2.47.2
    user: 1000:1000
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
      - --storage.tsdb.retention.time=14d
      - --storage.tsdb.retention.size=5GB
    volumes:
      - "{{ configuration_path }}/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro"
      - "{{ configuration_path }}/prometheus/web.yaml:/etc/prometheus/web.yml:ro"
      - "{{ configuration_path }}/prometheus/data:/prometheus/data"
    ports: [9090:9090]

  - name: grafana
    image: grafana/grafana:10.1.5
    user: 1000:1000
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    env:
      GF_DAGF_FEATURE_TOGGLES_ENABLE: publicDashboards
      GF_INSTALL_PLUGINS: "grafana-clock-panel, grafana-simple-json-datasource"
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: "{{ GRAFANA_ADMIN_PASSWORD }}"
    volumes:
      - "{{ configuration_path }}/grafana:/var/lib/grafana"
    ports: [3000:3000]

  - name: loki
    image: grafana/loki:2.9.0
    ports: [3100:3100]
    command: -config.file=/etc/loki/local-config.yaml

  - name: promtail
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
