---
# Set the user
common_user: chkpwd

service_definitions:
  - name: ark-server
    image: hermsi/ark-server:latest-1698728478
    ports:
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27020:27020/tcp"
      - "27015:27015/udp"
    env:
      SESSION_NAME: "The Ark - by Chkpwd."
      SERVER_MAP: "TheIsland"
      SERVER_PASSWORD: "{{ USR_PASSWORD_SOPS }}"
      ADMIN_PASSWORD: "{{ USR_PASSWORD_SOPS }}"
      MAX_PLAYERS: "5"
      UPDATE_ON_START: "true"
      BACKUP_ON_STOP: "true"
      PRE_UPDATE_BACKUP: "true"
      WARN_ON_STOP: "true"
      GAME_CLIENT_PORT: "7777"
      UDP_SOCKET_PORT: "7778"
      RCON_PORT: "27020"
      SERVER_LIST_PORT: "27015"
    volumes:
      - "/mnt/data/ark-server:/app"
      - "/mnt/data/ark-server/backups:/home/steam/ARK-Backups"
