---
common_user: chkpwd

buckets:
  - extras
  - main
  - versions
  - games
chocolates:
  # - geforce-game-ready-driver
scoops:
# Drivers
  # - nvcleanstall
# Games
  - sunshine
  - ryujinx
  - steam
  # - epic-games-launcher
  - playnite
