---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      nameOverride: *app

    controller:
        type: statefulset

    image:
      repository: freshrss/freshrss
      tag: 1.21.0

    env:
      TZ: "${TZ}"
      DOMAIN: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"

    hostname: *app

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Freshrss
          gethomepage.dev/group: Media Automation
          gethomepage.dev/icon: freshrss.png
          gethomepage.dev/description: RSS Feeds Manager
          gethomepage.dev/widget.type: "freshrss"
          gethomepage.dev/widget.url: "http://freshrss.tools.svc.cluster.local"
          gethomepage.dev/widget.username: "admin"
          gethomepage.dev/widget.password: ${APPS_PWD_FRESHRSS}
        hosts:
          - host: *host
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 1000
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /var/www/FreshRSS/data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn

    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        memory: 256Mi
