---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-monitoring-goldilocks
  namespace: flux-system
spec:
  path: ./kubernetes/core/monitoring/goldilocks-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
