---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
        type: statefulset

    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.1.0

    env:
      TZ: "${TZ}"
      SABNZBD__PORT: &port 8080
      SABNZBD__API_KEY: ${API_KEY_SABNZBD}
      SABNZBD__NZB_KEY: ${API_KEY_NZBGEEK}
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        {{ .Release.Name }},
        {{ .Release.Name }}.media,
        {{ .Release.Name }}.media.svc,
        {{ .Release.Name }}.media.svc.cluster,
        {{ .Release.Name }}.media.${CLUSTER_DOMAIN},
        {{ .Release.Name }}.local.chkpwd.com

    hostname: *app

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: int-ingress
        hosts:
          - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 1000
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn-media

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/
        mountPath: /data

    resources:
      requests:
        cpu: 200m
        memory: 350Mi
      limits:
        memory: 1000Mi
