---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 500Mi
              storageClass: longhorn-media
              globalMounts:
                - path: /config

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.1.0
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              SABNZBD__PORT: &port 8080
              SABNZBD__API_KEY: ${API_KEY_SABNZBD}
              SABNZBD__NZB_KEY: ${API_KEY_NZBGEEK}
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                {{ .Release.Name }},
                {{ .Release.Name }}.media,
                {{ .Release.Name }}.media.svc,
                {{ .Release.Name }}.media.svc.cluster,
                {{ .Release.Name }}.media.${CLUSTER_DOMAIN},
                {{ .Release.Name }}.${K8S_GATEWAY_DOMAIN}

            resources:
              requests:
                cpu: 10m
                memory: 180Mi
              limits:
                memory: 500Mi

          secondary:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v1.5.5
            env:
              PORT: &metricsPort 9707
              URL: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.${CLUSTER_DOMAIN}:8080"
              APIKEY: ${API_KEY_SABNZBD}
            args: ["sabnzbd"]

            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 125Mi

    service:
      main:
        primary: true
        ports:
          http:
            port: *port
      secondary:
        nameOverride: metrics
        controller: main
        ports:
          metrics:
            port: *metricsPort

    ingress:
      main:
        enabled: true
        className: int-ingress
        hosts:
          - host: &host "{{ .Release.Name }}.${K8S_GATEWAY_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
              - path: /metrics
                pathType: Prefix
                service:
                  name: secondary
                  port: metrics
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/
