---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.0.3

    env:
      TZ: "America/New_York"
      SABNZBD__API_KEY: ${API_KEY_SABNZBD}
      SABNZBD__NZB_KEY: ${API_KEY_NZBGEEK}
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        {{ .Release.Name }},
        {{ .Release.Name }}.media,
        {{ .Release.Name }}.media.svc,
        {{ .Release.Name }}.media.svc.cluster,
        {{ .Release.Name }}.media.svc.cluster.local,
        {{ .Release.Name }}.local.chkpwd.com

    hostname: *app

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Sabnzbd"
          gethomepage.dev/group: "Media Automation"
          gethomepage.dev/icon: "sabnzbd"
          gethomepage.dev/description: "Binary Newsreader"
          gethomepage.dev/widget.type: "sabnzbd"
          gethomepage.dev/widget.url: "http://sabnzbd.media.svc.cluster.local"
          gethomepage.dev/widget.key: "${API_KEY_SABNZBD}"
        hosts:
          - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/
        mountPath: /data

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [568]

    resources:
      requests:
        cpu: 200m
        memory: 350Mi
      limits:
        memory: 1000Mi
