---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:14.9-4
  primaryUpdateStrategy: unsupervised
  
  storage:
    size: 20Gi
    storageClass: longhorn-database
  
  superuserSecret:
    name: cloudnative-pg
  
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  
  monitoring:
    enablePodMonitor: true
