---
apiVersion: v1
kind: Service
metadata:
  name: postgres-loadBalancer
  namespace: databases
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${CNPG_LB_ADDRESS}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres
    role: primary