---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ytdl-sub
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          concurrencyPolicy: Forbid
          schedule: '*/15 * * * *'
          ttlSecondsAfterFinished: 86400
          startingDeadlineSeconds: 30
          successfulJobsHistory: 1
          failedJobsHistory: 1
          backoffLimit: 6

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: &context 1000
            runAsGroup: *context
            fsGroup: *context
            supplementalGroups:
              - 100
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/jmbannon/ytdl-sub
              tag: 2023.10.25.post3 
              pullPolicy: IfNotPresent

            env:
              TZ: "${TZ}"
              PUID: 568
              PGID: 568
              MEDIA_FOLDER: /media/youtube

            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1000Mi

    service:
      main:
        enabled: false

    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        name: "{{ .Release.Name }}-config"
        type: configMap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/downloads/youtube
        advancedMounts:
          main:
            main:
              - path: /media/youtube
      tmp:
        enabled: true
        type: emptyDir
        path: /tmp/ytdl-sub
