---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tautulli
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
        type: statefulset

    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.12.4

    env:
      TZ: "${TZ}"
      LOG_LEVEL: info
      PORT: &port 8181

    hostname: *app

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Tautulli
          gethomepage.dev/group: Media Automation
          gethomepage.dev/icon: tautulli.png
          gethomepage.dev/description: Media and activity statistics monitoring tool
          gethomepage.dev/widget.type: tautulli
          gethomepage.dev/widget.url: "http://tautulli.media.${CLUSTER_DOMAIN}"
          gethomepage.dev/widget.key: "${API_KEY_TAUTULLI}"
        hosts:
          - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 568
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn-media

    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        memory: 350Mi
