---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app linkding
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: sissbruecker/linkding
      tag: 1.21.1

    enableServiceLinks: false

    env:
      LD_SUPERUSER_NAME: chkpwd
      LD_SUPERUSER_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: linkding-secrets
            key: LD_SUPERUSER_PASSWORD
      LD_CSRF_TRUSTED_ORIGINS: "https://{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
      LD_DISABLE_URL_VALIDATION: true
      LD_DB_ENGINE: "postgres"
      LD_DB_HOST:
        valueFrom:
          secretKeyRef:
            name: linkding-pguser-linkding
            key: host
      LD_DB_PORT:
        valueFrom:
          secretKeyRef:
            name: linkding-pguser-linkding
            key: port
      LD_DB_DATABASE:
        valueFrom:
          secretKeyRef:
            name: linkding-pguser-linkding
            key: dbname
      LD_DB_USER:
        valueFrom:
          secretKeyRef:
            name: linkding-pguser-linkding
            key: user
      LD_DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: linkding-pguser-linkding
            key: password

    service:
      main:
        ports:
          http:
            port: 9090

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 13m
        memory: 64Mi
      limits:
        memory: 256Mi
