---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app node-feature-discovery
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.14.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    fullnameOverride: *app

    worker:
      config:
        core:
          sources: ["custom", "pci", "usb"]
        sources:
          usb:
            deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
            deviceLabelFields: ["class", "vendor", "device"]
