---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app minio
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      interval: 30m
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-09-07T22-25-02Z

    env:
      TZ: ${TZ}
      MINIO_UPDATE: "off"
      MINIO_PROMETHEUS_URL: http://prometheus-prometheus.monitoring.${CLUSTER_DOMAIN}:9090
      MINIO_PROMETHEUS_JOB_ID: minio
      MINIO_BROWSER_REDIRECT_URL: "https://minio.${LOCAL_DOMAIN}"
      MINIO_SERVER_URL: "https://s3.${LOCAL_DOMAIN}"

    envFrom:
      - secretRef:
          name: *app
    args: ["server", "/data", "--console-address", ":9001"]

    service:
      main:
        enabled: true
        ports:
          http:
            port: &port-console 9001
          api:
            enabled: true
            port: &port-api 9000

    ingress:
      main:
        enabled: true
        ingressClassName: int-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host-console "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-console
          - host: &host-api "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-api
        tls:
          - hosts:
              - *host-console
              - *host-api

    podSecurityContext:
      runAsUser: &context 568
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [100]

    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: longhorn-config
        mountPath: /data

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 750Mi
