---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wizarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      nameOverride: *app

    image:
      repository: ghcr.io/wizarrrr/wizarr
      tag: 2.2.0

    controller:
        type: statefulset

    env:
      TZ: "${TZ}"
      APP_URL: https://{{ .Release.Name }}.${LOCAL_DOMAIN}
      DISABLE_BUILTIN_AUTH: "true"

    hostname: *app

    service:
      main:
        ports:
          http:
            port: &port 5690

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: wizarr
          gethomepage.dev/group: Media Automation
          gethomepage.dev/icon: "https://github.com/Wizarrrr/wizarr/blob/master/screenshots/wizard.png"
          gethomepage.dev/description: Plex Registration Tool
          gethomepage.dev/widget.url: "http://wizarr.media.svc.cluster.local"
        hosts:
          - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 1000
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /data/database
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn

    resources:
      requests:
        cpu: 10m
        memory: 100M
      limits:
        memory: 200M
