---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wizarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    image:
      repository: ghcr.io/wizarrrr/wizarr
      tag: dev

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    env:
      TZ: "${TZ}"
      APP_URL: https://{{ .Release.Name }}.${EXTERNAL_DOMAIN}
      DISABLE_BUILTIN_AUTH: "false"

    hostname: *app

    service:
      main:
        ports:
          http:
            port: &port 5690

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 1000
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /data/database
        accessMode: ReadWriteOnce
        size: 300Mi
        storageClass: longhorn-media

    resources:
      requests:
        cpu: 10m
        memory: 100M
      limits:
        memory: 200M
