---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-recurring-jobs
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn-recurring-jobs
      version: 5.0.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system

  values:
    minuteStep: 5
    hourStep: 2
    createStorageClasses: true
    storageclass:
      allowVolumeExpansion: true
      reclaimPolicy: Retain

    parameters:
      replicaAutoBalance: best-effort
      dataLocality: best-effort
      numberOfReplicas: 3
      staleReplicaTimeout: 30

    groups:
      "Database":
        snapshot:
          - interval: 10m
            retain: 6
        backup:
          - interval: 12h
            retain: 2
      "Config":
        snapshot:
          - interval: 10m
            retain: 6
        backup:
          - interval: 24h
            retain: 7
      "Media":
        snapshot:
          - interval: 10m
            retain: 6
        backup:
          - interval: 24h
            retain: 2
      "Clusters":
        snapshot:
          - interval: 10m
            retain: 1
        backup:
          - interval: 24h
            retain: 1