---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ark-cluster
  namespace: game-servers
spec:
  interval: 15m
  chart:
    spec:
      chart: ark-cluster
      version: 0.1.14
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: ark-cluster
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

values:
  fullnameOverride: *app

  commonAnnotations:
    metallb.universe.tf/loadBalancerIPs: ${ARK_CLUSTER_LB_ADDRESS}

  image:
    repository: drpsychick/arkserver
    tag: latest-v1.6.62
    pullPolicy: IfNotPresent

  updateStrategy:
    type: Recreate

  # Time for the server to shutdown gracefully
  terminationGracePeriodSeconds: 60

  # Defaults to 1, we set this to 0 so servers don't start automatically after deploy
  replicaCount: 0

  clusterName: *app

  # Mods available in the cluster and enabled by default on all servers.
  # Mods are updated with the game and can be overwritten per server.
  mods: []
  #  - "731604991"
  #  - "889745138"
  #  - "893904615"
  #  - "1404697612"
  #  - "621154190"
  #  - "564895376"
  #  - "931434275"

  # Set RCON password for the whole cluster
  rcon:
    password: "foobar"

  # Global extraEnvVars for all servers
  extraEnvVars:
    # - name: am_arkwarnminutes
    #   value: "15"

  # Global custom game settings can be overwritten per server
  customConfigMap:
    GameIni:
    GameUserSettingsIni:
    EngineIni:

  # Servers in the ARK cluster
  servers:
  # one entry for each server in the cluster
    extinction:
      # updateOnStart should be enabled only on the first server
      updateOnStart: true
      sessionName: "Extinction"
      message: "Welcome to Bryan's Ark Server - Map: Extinction"
      # map: TheIsland, Ragnarok, CrystalIsles, Aberration_P, ScorchedEarth_P, Extinction, ...
      map: Extinction
      password: "testing"
      maxPlayers: 10
      # xpMultiplier is added to default GameUserSettings.ini
      # if you use `customConfigMap.GameUserSettingsIni` make sure to include it there
      xpMultiplier: 6
      extraEnvVars:
        - name: am_arkwarnminutes
          value: "30"
      ports:
        queryudp: 27010
        gameudp: 7770
        rcon: 32330
      mods: []
      rcon:
        password: "foobar"
      resources:
        requests:
          cpu: 1
          memory: 4Gi
        limits:
          memory: 6Gi
      customConfigMap:
        GameIni: |
          # Extinction Game.ini
        GameUserSettingsIni: |
          # Extinction GameUserSettings.ini
          [ServerSettings]
          XPMultiplier=6
        EngineIni: |
          # Extinction Engine.ini

  resources:
    requests:
      cpu: 1
      memory: 6Gi
    limits:
      memory: 8Gi

  # Default ports used by the container. Can be set per server.
  # ARK communicates ports to the client, so make sure the container port matches the external port!
  # Using these default settings for a cluster only makes sense if you have an IP for each server.
  containerPorts:
    gameudp: 7777
    queryudp: 27015
    rcon: 32330

  service:
    enabled: true
    externalTrafficPolicy: Local
    type: LoadBalancer
    metallb_shared_ip: false

  persistence:
    enabled: true
    # game files from steam, the largest volume, includes installed mods
    game:
      storageClass: game-servers
      accessModes:
        - ReadOnlyMany
        - ReadWriteMany
        - ReadWriteOnce
      size: 30Gi
      mountPath: /arkserver

    # shared cluster files
    cluster:
      storageClass: game-servers
      accessModes:
        - ReadWriteMany
      size: 200Mi
      mountPath: /arkserver/ShooterGame/Saved/clusters

    save:
      storageClass: game-servers
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      mountPath: /arkserver/ShooterGame/Saved

  startupProbe:
    initialDelaySeconds: 120 # 120s + 60*10s = 720s max
    failureThreshold: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  livenessProbe:
    initialDelaySeconds: 10 # unhealthy after max 3*10s = 30s
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  podAnnotations:
    secret.reloader.stakater.com/reload: *app

  podSecurityContext:
    capabilities:
      drop:
        - ALL
      add:
        - CHOWN
        - NET_BIND_SERVICE
    readOnlyRootFilesystem: true
    runAsNonRoot: false
