---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    vsphere:
      children:
        esxi_hosts:
        vcenter:

    vcenter:
      hosts:
        ronin:

    esxi_hosts:
      hosts:
        # esx[1:3]:
        octane:
        caustic:

    guests:
      children:
        docker_hosts:
        media_server:
        k3s_cluster:
      hosts:
        cockpit:

    linux:
      hosts:
        mirage:
        home-assistant:
        cockpit:
        kubes-cp-1:
        kubes-cp-2:
        kubes-cp-3:
        stable-diffusion:
        boot-server:
        dns-srv-01:
        dns-srv-02:

    windows:
      hosts:
        loba:
          ansible_host: 172.16.16.100
          ansible_user: chkpwd
          ansible_become_method: runas
          ansible_become_user: chkpwd
        bloodhound:

    docker_hosts:
      hosts:
        mirage:
        home-assistant:
        ct-01-x86:
        ct-02-x86:
        boot-server:
        dns-srv-01:
        dns-srv-02:

    k3s_cluster:
      children:
        k3s_master:
        #workers:

    k3s_master:
      hosts:
        kubes-cp-1:
          ansible_host: 172.16.16.10
        kubes-cp-2:
          ansible_host: 172.16.16.11
        kubes-cp-3:
          ansible_host: 172.16.16.12

    printers:
      hosts:
        rampart:
      vars:
        ansible_user: pi
        ansible_become_user: pi

    media_server:
      hosts:
        mirage:

    cloud:
      vars:
        ansible_remote_user: ubuntu
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/oci
        common_user: ubuntu
      hosts:
        ct-01-x86:
          ansible_host:	129.80.241.202
        ct-02-x86:
          ansible_host: 150.136.245.5

    dns_servers:
      hosts:
        dns-srv-01:
        dns-srv-02:

    onprem:
      children:
        vsphere:

    datacenter:
      children:
        cloud:
        onprem:
