---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    hypervisors:
      esxi_hosts:
      proxmox_nodes:

    proxmox_nodes:
      hosts:
        pve-srv-01:
          ansible_ssh_user: root

    vsphere:
      children:
        esxi_hosts:
        vcenter:

    esxi_hosts:
      hosts:
        octane:

    guests:
      children:
        docker_hosts:
        media_server:
        k3s_cluster:
      hosts:

    linux:
      hosts:
        media-srv-01:
        home-assistant:

        kubes-cp-[1:3]:
        mgmt-srv-01:
        dns-srv-02:
        hosting-srv-01:

    windows:
      vars:
        ansible_become_method: runas
      hosts:
        chk-dev-win11:
          ansible_host: 172.16.16.100
          ansible_user: chkpwd
          ansible_become_user: chkpwd

    docker_hosts:
      hosts:
        media-srv-01:
        home-assistant:
        ct-01-ec2:
        mgmt-srv-01:
        dns-srv-02:
        hosting-srv-01:

    k3s_cluster:
      children:
        k3s_master:

    k3s_master:
      hosts:
        kubes-cp-1:
          ansible_host: 172.16.16.10
        kubes-cp-2:
          ansible_host: 172.16.16.11
        kubes-cp-3:
          ansible_host: 172.16.16.12

    printers:
      hosts:
        rampart:
      vars:
        ansible_user: pi
        ansible_become_user: pi

    media_server:
      hosts:
        media-srv-01:

    aws:
      vars:
        ansible_remote_user: admin
        ansible_ssh_user: admin
        ansible_ssh_private_key_file: ~/.ssh/aws
        common_user: admin
      hosts:
        ct-01-ec2:
          ansible_host:	54.145.97.133

    oci:
      vars:
        ansible_remote_user: ubuntu
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/oci
        common_user: ubuntu
      hosts:
        ct-01-oci:
          ansible_host:	129.80.54.203
        ct-02-oci:
          ansible_host:	141.148.13.11

    cloud:
      children:
        aws:
        oci:

    dns_servers:
      hosts:
        mgmt-srv-01:
        dns-srv-02:
    
    game_servers:
      hosts:
        hosting-srv-01:
          ansible_ssh_user: chkpwd

    onprem:
      children:
        vsphere:

    datacenter:
      children:
        cloud:
        onprem:
