---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    vsphere:
      children:
        esxi_hosts:
        vcenter:

    esxi_hosts:
      hosts:
        # esx[1:3]:
        octane:
        caustic:

    guests:
      children:
        docker_hosts:
        media_server:
        k3s_cluster:
      hosts:
        cockpit:

    linux:
      hosts:
        media-srv-01:
        home-assistant:
        cockpit:
        kubes-cp-1:
        kubes-cp-2:
        kubes-cp-3:
        boot-server:
        mgmt-srv-01:
        dns-srv-02:
        hosting-srv-01:

    windows:
      vars:
        ansible_become_method: runas
      hosts:
        loba:
          ansible_host: 172.16.16.100
          ansible_user: chkpwd
          ansible_become_user: chkpwd
        win10-gaming-01:
          ansible_host: 172.16.30.11
          ansible_user: chkpwd
          ansible_become_user: chkpwd

    docker_hosts:
      hosts:
        media-srv-01:
        home-assistant:
        ct-01-ec2:
        boot-server:
        mgmt-srv-01:
        dns-srv-02:
        hosting-srv-01:

    k3s_cluster:
      children:
        k3s_master:
        #workers:

    k3s_master:
      hosts:
        kubes-cp-1:
          ansible_host: 172.16.16.10
        kubes-cp-2:
          ansible_host: 172.16.16.11
        kubes-cp-3:
          ansible_host: 172.16.16.12

    printers:
      hosts:
        rampart:
      vars:
        ansible_user: pi
        ansible_become_user: pi

    media_server:
      hosts:
        media-srv-01:

    cloud:
      vars:
        ansible_remote_user: admin
        ansible_ssh_user: admin
        ansible_ssh_private_key_file: ~/.ssh/aws
        common_user: admin
      hosts:
        ct-01-ec2:
          ansible_host:	54.145.97.133

    dns_servers:
      hosts:
        mgmt-srv-01:
        dns-srv-02:
    
    game_servers:
      hosts:
        hosting-srv-01:
          ansible_ssh_user: chkpwd

    onprem:
      children:
        vsphere:

    datacenter:
      children:
        cloud:
        onprem:
