---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  dependsOn:
    - name: immich-server
      namespace: tools
    - name: immich-redis
      namespace: tools

  values:
    controller:
      strategy: RollingUpdate

    global:
      fullnameOverride: *app
    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      tag: v1.66.1

    service:
      main:
        ports:
          http:
            port: 3003

    persistence:
      cache:
        enabled: true
        type: emptyDir
      library:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/images
        mountPath: /usr/src/app/upload

    # this is necessary for the downloads to complete
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-cm

    resources:
      requests:
        cpu: 100m
        memory: 250Mi
