---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app shlink
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: shlinkio/shlink
      tag: 3.6.3-non-root

    env:
      DEFAULT_DOMAIN: &host "i.${EXTERNAL_DOMAIN}"
      IS_HTTPS_ENABLED: true
      GEOLITE_LICENSE_KEY:
        valueFrom:
          secretKeyRef:
            name: shlink-secrets
            key: GEOLITE_LICENSE_KEY
      DEFAULT_SHORT_CODES_LENGTH: 4
      ENABLE_PERIODIC_VISIT_LOCATE: true
      PORT: &port 80
      TIMEZONE: ${TZ}
      DB_DRIVER: postgres
      DB_NAME:
        valueFrom:
          secretKeyRef:
            name: shlink-pguser-shlink
            key: dbname
      DB_USER:
        valueFrom:
          secretKeyRef:
            name: shlink-pguser-shlink
            key: user
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: shlink-pguser-shlink
            key: password
      DB_HOST:
        valueFrom:
          secretKeyRef:
            name: shlink-pguser-shlink
            key: host
      DB_PORT:
        valueFrom:
          secretKeyRef:
            name: shlink-pguser-shlink
            key: port
      INITIAL_API_KEY: ${API_KEY_SHLINK}

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
