---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases-cloudnative-pg
  namespace: flux-system
spec:
  dependsOn:
    - name: databases-cloudnative-pg-config
  path: ./kubernetes/core/databases/cloudnative-pg/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases-cloudnative-pg-config
  namespace: flux-system
spec:
  path: ./kubernetes/core/databases/cloudnative-pg/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
