---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.5

    env:
      TZ: "${TZ}"
      QBITTORRENT__PORT: &port 8080

    sidecars:
      vuetorrent:
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        imagePullPolicy: IfNotPresent
        args:
          - --repo=https://github.com/WDaan/VueTorrent
          - --branch=latest-release
          - --wait=86400
          - --root=/add-ons
        volumeMounts:
          - { name: add-ons, mountPath: /add-ons }

    hostname: *app

    service:
      main:
        ports:
          http:
            port: *port

    podAnnotations:
      setGateway: "true"

    ingress:
      main:
        enabled: true
        ingressClassName: int-ingress
        hosts:
          - host: &host "{{ .Release.Name }}.${K8S_GATEWAY_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 1000
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 200Mi
        storageClass: longhorn-media

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/downloads/torrents
        mountPath: /data
      add-ons:
        enabled: true
        type: emptyDir
    
    resources:
      requests:
        cpu: 200m
        memory: 350Mi
      limits:
        memory: 1000Mi
