---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        type: statefulset
        strategy: 
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 200Mi
              storageClass: longhorn-media
              globalMounts:
                - path: /config

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: &context 1000
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.2

            env:
              TZ: "${TZ}"
              QBITTORRENT__PORT: &port 8080
              QBT_Preferences__WebUI__AlternativeUIEnabled: 'false'
              QBT_BitTorrent__Session__DefaultSavePath: '/data/complete'
              QBT_BitTorrent__Session__TempPath: '/data/incomplete'
              QBT_BitTorrent__Session__TempPathEnabled: 'true'
              QBT_BitTorrent__Session__FinishedTorrentExportDirectory: '/data/files'
              QBT_BitTorrent__Session__TorrentExportDirectory: '/data/files'
              QBT_BitTorrent__Session__Port: '50413'
              QBT_BitTorrent__WebUI__RootFolder: 'true'
    
            probes:
              liveness:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 2000Mi

          secondary:
            image: 
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.1.0
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --branch=latest-release
              - --wait=86400
              - --root=/add-ons
    
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 125Mi
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: int-ingress
        hosts:
          - host: &host "{{ .Release.Name }}.${K8S_GATEWAY_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: nfs
        server: "nas-srv-01.${LOCAL_DOMAIN}"
        path: /volume1/vault-01/downloads/torrent
      add-ons:
        enabled: true
        type: emptyDir
        advancedMounts:
          main:
            secondary:
              - path: /add-ons
