---
linux_cmdline:
  cpu:
    amd: "amd_iommu=on "
    intel: "intel_iommu=on "
  iommu_passthrough:
    "on": "iommu=pt "
    "off": ""
  disable_vga:
    "on": "vfio_pci.disable_vga=1 "
    "off": ""
  initcall_blacklist:
    "on": "initcall_blacklist=sysfb_init "
    "off": ""
  acs_override:
    "ds,mf": "pcie_acs_override=downstream,multifunction "
    "off": ""
