---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app recyclarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
      type: cronjob
      cronjob:
        schedule: '@daily'

    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: 5.1.1
    command: ['/app/recyclarr/recyclarr']
    args: ['sync']

    env:
      TZ: ${TZ}
      API_KEY_SONARR:
        valueFrom:
          secretKeyRef:
            name: media-secrets
            key: API_KEY_SONARR
      API_KEY_RADARR:
        valueFrom:
          secretKeyRef:
            name: media-secrets
            key: API_KEY_RADARR

    service:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        type: configMap
        name: recyclarr-cm
        mountPath: /config/recyclarr.yml
        subPath: recyclarr.yml
        readOnly: true

    resources:
      requests:
        cpu: 10m
        memory: 50M
      limits:
        memory: 100M
