---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app recyclarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          concurrencyPolicy: Forbid
          schedule: '@daily'
          startingDeadlineSeconds: 30
          successfulJobsHistory: 1
          failedJobsHistory: 1
          backoffLimit: 6

        pod:
          securityContext:
            runAsUser: &context 1999
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 6.0.2

            command: ['/app/recyclarr/recyclarr']
            args: ['sync']

            env:
              TZ: ${TZ}
              API_KEY_SONARR:
                valueFrom:
                  secretKeyRef:
                    name: media-secrets
                    key: API_KEY_SONARR
              API_KEY_RADARR:
                valueFrom:
                  secretKeyRef:
                    name: media-secrets
                    key: API_KEY_RADARR

            securityContext:
              allowPrivilegeEscalation: false

            resources:
              requests:
                cpu: 5m
                memory: 36M
              limits:
                memory: 128M

    service:
      main:
        enabled: false

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-cm
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
