---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              accessMode: ReadWriteOnce
              size: 2Gi
              storageClass: longhorn-media

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: &context 1000
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.0.697
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              SONARR__INSTANCE_NAME: *app
              SONARR__PORT: &port 8989
              SONARR__APPLICATION_URL: "https://{{ .Release.Name }}.${K8S_GATEWAY_DOMAIN}"
              SONARR__API_KEY: ${API_KEY_SONARR}
              SONARR__AUTHENTICATION_METHOD: External
              SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              SONARR__LOG_LEVEL: info

            resources:
              requests:
                cpu: 200m
                memory: 250Mi
              limits:
                memory: 1000Mi

          secondary:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v1.5.5
            env:
              PORT: &metricsPort 9707
              URL: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.${CLUSTER_DOMAIN}:8989"
              APIKEY: ${API_KEY_SONARR}
            args: ["sonarr"]

            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 200Mi

    service:
      main:
        ports:
          http:
            port: *port
      secondary:
        nameOverride: metrics
        controller: main
        ports:
          metrics:
            port: *metricsPort

    ingress:
      main:
        enabled: true
        className: int-ingress
        hosts:
          - host: &host "{{ .Release.Name }}.${K8S_GATEWAY_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
              - path: /metrics
                pathType: Prefix
                service:
                  name: sonarr-metrics
                  port: metrics

        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/
        mountPath: /data
