---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lynx
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: jackbailey/lynx
      tag: 1.8.0-beta

    env:
      NODE_ENV: production
      DB_USER: root
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: lynx-mongodb
            key: mongodb-root-password
      JWT_KEY:
        valueFrom:
          secretKeyRef:
            name: lynx-secrets
            key: JWT_TOKEN
      URL_LENGTH: 8
      URL_SET: standard
      URL_ONLY_UNIQUE: false
      HOME_REDIRECT: /dash/overview
      FORCE_FRONTEND_REDIRECT: true
      ENABLE_REGISTRATION: false # First registration will always be allowed
      DOMAIN: https://i.${EXTERNAL_DOMAIN}
      USE_HTTPS: true
      CORS: "*"
      BACKUP: true
      BACKUP_SCHEDULE: "0 1 * * *"
      BACKUP_COUNT: 5
      URL_REGEX: 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#: ]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//: ]*)'

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "i.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          hosts:
              *host

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 250Mi
