---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: misc
spec:
  interval: 15m
  chart:
    spec:
      chart: podinfo
      version: 6.5.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system

  values:
    ingress:
      enabled: true
      className: int-ingress
      hosts:
        - host: &host "{{ .Release.Name }}.${K8S_GATEWAY_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
