---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development-awx
  namespace: flux-system
spec:
  dependsOn:
    - name: development-awx-postgres
    - name: development-awx-operator
  path: ./kubernetes/apps/development/awx-operator/multi-app/awx
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development-awx-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: development-awx-config
    - name: development-awx-postgres
  path: ./kubernetes/apps/development/awx-operator/multi-app/awx-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development-awx-postgres
  namespace: flux-system
spec:
  dependsOn:
    - name: development-awx-config
  path: ./kubernetes/apps/development/awx-operator/multi-app/awx-postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development-awx-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/development/awx-operator/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
