---
- name: Create Git directory
  ansible.builtin.file:
    path: "/home/{{ common_user }}/code/boilerplates"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: '0755'
  become: false
  register: repo

- name: Check if the directory exists
  ansible.builtin.stat:
    path: /home/{{ common_user }}/code/boilerplates/ansible
  register: repo_directory

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/chkpwd/boilerplates.git
    dest: /home/{{ common_user }}/code/boilerplates
  when: not repo_directory.stat.exists
  become: false
