---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - sabnzbd-secrets.sops.yaml
configMapGenerator:
  - name: sabnzbd-config
    files:
      - sabnzbd-config=./sabnzbd-config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
