---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authentik
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.8.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    ingress:
      enabled: true
      ingressClassName: ext-ingress
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Authentik
        gethomepage.dev/group: Security
        gethomepage.dev/icon: authentik.png
        gethomepage.dev/description: Authentication and authorization management
        gethomepage.dev/widget.type: authentik
        gethomepage.dev/widget.url: "http://authentik.security.${CLUSTER_DOMAIN}"
        gethomepage.dev/widget.key: "${API_KEY_AUTHENTIK}"
        external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
      hosts:
        - host: &host "authentik.${EXTERNAL_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    envFrom:
      secretRef:
      name: authentik-secrets

    authentik:
      error_reporting:
        enabled: true

      email:
        from: "authentik <ocid@chkpwd.com>"
        host: smtp.gmail.com
        port: 465
        use_ssl: false

    postgresql:
      enabled: true

    redis:
      enabled: true

    prometheus:
      serviceMonitor:
        create: true

    resources:
      server:
        requests:
          cpu: 200m
        limits:
          memory: 500Mi