---
- name: Converge
  hosts: all
  gather_facts: false

  vars:
    docker_edition: 'ce'
    docker_package_state: latest

  pre_tasks:
    - name:
      become: true
      vars: 
        ansible_user: 'root'
      block:
        - name: Gather facts from container
          ansible.builtin.gather_facts:

        - name: "Install sudo on Debian family"
          ansible.builtin.apt:
            update_cache: true
            pkg: "sudo"
          become: true
          when: "ansible_os_family == 'Debian'"

        - name: Create a login user
          ansible.builtin.user:
            name: "ansible"
            password: 'password'
            groups:
              - "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
            state: present
            # append: true # If false, the above groups are the only groups provided to the user

        - name: Allow sudo group to have passwordless sudo
          ansible.builtin.lineinfile:
            path: /etc/sudoers
            state: present
            regexp: '^%sudo'
            line: '%sudo ALL=(ALL) NOPASSWD: ALL'
            validate: '/usr/sbin/visudo -cf %s'

    
    - name: Gather facts from container
      ansible.builtin.gather_facts:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      become: true

    - name: Wait for systemd to complete initialisation # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1
      become: true

    - debug: var=systemctl_status

  roles:
    - role: system
