---
- name: Configure SWAG instance
  hosts: ct-01-aarch64
  become: false

  tasks:
    - name: Create swag directories
      ansible.builtin.file: # noqa risky-file-permissions
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ swag_app_dir }}/dns-conf"
        - "{{ swag_app_dir }}/nginx/site-confs"

    - name: Template NGINX config
      ansible.builtin.template:
        src: ../../files/nginx.conf.j2
        dest: "{{ swag_app_dir }}/nginx/site-confs/default.conf"
        mode: '664'

    - name: Copy Cloudflare config
      ansible.builtin.copy:
        content: |
          dns_cloudflare_api_token = "{{ CF_API_TOKEN }}"
        dest: "{{ swag_app_dir }}/dns-conf/cloudflare.ini"
        mode: '400'
