---
- name: Configure SWAG instance
  hosts: cloud
  become: true

  tasks:
    - name: Create swag directories
      delegate_to: ct-01-ec2
      ansible.builtin.file: # noqa risky-file-permissions
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ configuration_path }}/swag/dns-conf"
        - "{{ configuration_path }}/swag/nginx/site-confs"

    - name: Template NGINX config
      delegate_to: ct-01-ec2
      ansible.builtin.template:
        src: ../../files/nginx.conf.j2
        dest: "{{ configuration_path }}/swag/nginx/site-confs/default.conf"
        mode: '664'

    - name: Copy Cloudflare config
      delegate_to: ct-01-ec2
      ansible.builtin.copy:
        content: |
          dns_cloudflare_api_token = "{{ SWAG_CF_API_TOKEN }}"
        dest: "{{ configuration_path }}/swag/dns-conf/cloudflare.ini"
        mode: '400'

    - name: Create network(s)
      delegate_to: ct-01-ec2
      community.docker.docker_network:
        name: "{{ item.name }}"
        ipam_config:
          - subnet: "172.23.{{ item.octet }}.0/24"
            gateway: "172.23.{{ item.octet }}.1"
            iprange: "172.23.{{ item.octet }}.0/26"
      loop:
        - name: net_swag
          octet: 28
