---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-microservices
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  dependsOn:
    - name: immich-server
    - name: immich-typesense

  values:
    global:
      fullnameOverride: *app

    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.74.0
    args: ["start-microservices.sh"]

    env:
      DB_DATABASE:
        valueFrom: 
          secretKeyRef:
            name: immich-pguser-immich
            key: dbname
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: immich-pguser-immich
            key: host
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-pguser-immich
            key: user
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-pguser-immich
            key: password
      DB_URL:
        valueFrom:
          secretKeyRef:
            name: immich-pguser-immich
            key: uri

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-cm

    service:
      main:
        enabled: false

    persistence:
      library:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/images
        mountPath: /usr/src/app/upload

    resources:
      requests:
        cpu: 5m
        memory: 277Mi
      limits:
        memory: 512Mi
