---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app winxuu
  namespace: personal
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
      main:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          main:
            image:
              repository: ghcr.io/chkpwd/winxuu
              tag: 2.0.1
              pullPolicy: IfNotPresent

          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

    service:
      main:
        ports:
          http:
            port: &port 3389

    ingress:
      main:
        enabled: true
        className: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    defaultPodOptions:
      securityContext:
        runAsUser: &context 65532
        runAsGroup: *context
        fsGroup: *context
        fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config:
        enabled: false

    resources:
      requests:
        cpu: 10m
        memory: 50M
      limits:
        memory: 50M
