---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app winxuu
  namespace: personal
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: &context 65532
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/chkpwd/winxuu
              tag: 2.0.1
              pullPolicy: IfNotPresent

            resources:
              requests:
                cpu: 10m
                memory: 50M
              limits:
                memory: 50M

    service:
      main:
        ports:
          http:
            port: 3389

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        enabled: true
        className: ext-ingress
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
