---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      interval: 30m
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    fullnameOverride: *app
    
    provider: cloudflare
    env:
      CF_API_TOKEN: ${CLOUDFLARE_API_TOKEN}

    extraArgs:
      - --ingress-class=nginx
      - --zone-id-filter=${CLOUDFLARE_ZONE_ID}
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint

    policy: sync

    sources: ["crd", "ingress"]
    
    txtPrefix: k8s.
    txtOwnerId: default
    
    domainFilters: ["${EXTERNAL_DOMAIN}"]

    serviceMonitor:
      enabled: true
