---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      interval: 30m
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    recommender:
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 0.14.0
      enabled: true

      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
        storage: prometheus
        prometheus-address: http://prometheus-prometheus.monitoring.${CLUSTER_DOMAIN}:9090

      requests:
        cpu: 15m
        memory: 110M
      limits:
        memory: 316M

    updater:
      enabled: false