---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 15m
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.23.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system

  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    image:
      repository: ghcr.io/actions-runner-controller/actions-runner-controller
    authSecret:
      create: true
      github_token: ${ACTION_RUNNER_GIT_TOKEN}
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    githubWebhookServer:
      enabled: true
      logFormat: json

    metrics:
      serviceMonitor: false
      port: 8080
      proxy:
        enabled: false
    actionsMetrics:
      serviceMonitor: false
      port: 8080
      proxy:
        enabled: false
    actionsMetricsServer:
      enabled: true

    resources:
      requests:
        cpu: 10m
        memory: 250M
      limits:
        memory: 450M
