---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app screego
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    image:
      repository: ghcr.io/screego/server
      tag: 1.10.0

    env:
      TZ: ${TZ}
      SCREEGO_EXTERNAL_IP: ${PUBLIC_IP}
      SCREEGO_SERVER_TLS: "false"
      SCREEGO_AUTH_MODE: all
      SCREEGO_LOG_LEVEL: info
      SCREEGO_PROMETHEUS: "true"
      SCREEGO_CLOSE_ROOM_WHEN_OWNER_LEAVES: "true"

    service:
      main:
        ports:
          http:
            port: 5050
          stun:
            port: 3478

    hostname: *app

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 35m
        memory: 300Mi
      limits:
        memory: 500Mi
