---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app screego
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    image:
      repository: ghcr.io/screego/server
      tag: 1.10.1

    env:
      TZ: ${TZ}
      SCREEGO_EXTERNAL_IP: ${PUBLIC_IP}
      SCREEGO_SERVER_TLS: "false"
      SCREEGO_AUTH_MODE: all
      SCREEGO_USERS_FILE: /var/screego/users
      SCREEGO_LOG_LEVEL: info
      SCREEGO_PROMETHEUS: "true"
      SCREEGO_CLOSE_ROOM_WHEN_OWNER_LEAVES: "true"
      SCREEGO_TRUST_PROXY_HEADERS: "true"

    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 172.16.16.206
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 5050
          stun:
            port: 3478

    hostname: *app

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: secret
        name: screego-secrets
        mountPath: /var/screego

    resources:
      requests:
        cpu: 35m
        memory: 300Mi
      limits:
        memory: 500Mi
