---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-node-feature-discovery
  namespace: flux-system
spec:
  path: ./kubernetes/core/management/node-feature-discovery-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: core-node-feature-discovery-features
#   namespace: flux-system
# spec:
#   path: ./kubernetes/core/management/node-feature-discovery-system/features
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: chkpwd-ops
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
