---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kavita
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
        type: statefulset
    
    image:
      repository: kizaing/kavita
      tag: 0.7.3

    env:
      TZ: "${TZ}"

    hostname: *app

    service:
      main:
        ports:
          http:
            port: &port 5000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Kavita
          gethomepage.dev/group: Media Automation
          gethomepage.dev/icon: kavita.png
          gethomepage.dev/description: Cross platform reading server
          gethomepage.dev/href: "http://kavita.media.svc.cluster.local"
        hosts:
          - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 1000
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /kavita/config 
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/reading
        mountPath: /data

    resources:
      requests:
        cpu: 25m
        memory: 350Mi
      limits:
        memory: 1000Mi
