---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kavita
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    
    image:
      repository: kizaing/kavita
      tag: 0.7.8

    env:
      TZ: "${TZ}"

    hostname: *app

    service:
      main:
        ports:
          http:
            port: 5000

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 1000
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /kavita/config 
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn-media

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/reading
        mountPath: /data

    resources:
      requests:
        cpu: 25m
        memory: 350Mi
      limits:
        memory: 1000Mi
