---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kavita
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /kavita/config
              accessMode: ReadWriteOnce
              size: 300Mi
              storageClass: longhorn-media

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: &context 1000
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: kizaing/kavita
              tag: 0.7.8
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"

            resources:
              requests:
                cpu: 25m
                memory: 350Mi
              limits:
                memory: 1000Mi

    service:
      main:
        ports:
          http:
            port: 5000

    ingress:
      main:
        enabled: true
        className: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/reading
        mountPath: /data
