apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app longhorn
  namespace: &namespace storage
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.5.1
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    ingress:
      enabled: true
      ingressClassName: int-ingress
      host: longhorn.${K8S_GATEWAY_DOMAIN}
      tls: true
      secureBackends: true
      tlsSecret: longhorn-tls
      path: /

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Retain
      recurringJobSelector:
        enable: false

    monitoring:
      enabled: true
      createPrometheusRules: true

    defaultSettings:
      defaultReplicaCount: 3
      backupTarget: nfs://cockpit.${LOCAL_DOMAIN}:/mnt/data/backup/longhorn
      backupstorePollInterval: 60
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultDataPath: /mnt/data/longhorn
      defaultDataLocality: best-effort
      defaultLonghornStaticStorageClass: longhorn
      storageMinimalAvailablePercentage: 0
      storageReservedPercentageForDefaultDisk: 0
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      restoreVolumeRecurringJobs: true
