apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    ingress:
      enabled: true
      ingressClassName: int-ingress
      host: longhorn.${K8S_GATEWAY_DOMAIN}
      tls: true
      secureBackends: true
      tlsSecret: longhorn-tls
      path: /

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Retain
      recurringJobSelector:
        enable: false

    monitoring:
      enabled: true
      createPrometheusRules: true

    defaultSettings:
      backupTarget: nfs://cockpit.${LOCAL_DOMAIN}:/mnt/data/backup/longhorn
      backupstorePollInterval: 60
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultDataPath: /var/lib/longhorn
      defaultDataLocality: best-effort
      defaultLonghornStaticStorageClass: longhorn
      storageMinimalAvailablePercentage: 0
      storageReservedPercentageForDefaultDisk: 0
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      allowRecurringJobWhileVolumeDetached: false
      autoCleanupSystemGeneratedSnapshot: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      disableSchedulingOnCordonedNode: true
      defaultReplicaCount: 3
      engineReplicaTimeout: 8
      failedBackupTTL: 1440
      restoreVolumeRecurringJobs: false
      snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: false
      snapshotDataIntegrityCronjob: 0 8 */7 * *
      upgradeChecker: false
      v2DataEngine: false
