---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-radarr
  namespace: flux-system
spec:
  dependsOn:
    - name: media-radarr-config
  path: ./kubernetes/apps/media/radarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-radarr-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/radarr/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
