---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-external-nginx
  namespace: flux-system
spec:
  path: ./kubernetes/core/networking/nginx-ext-ingress-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-external-nginx-services
  namespace: flux-system
spec:
  dependsOn:
    - name: core-external-nginx
  path: ./kubernetes/core/networking/nginx-ext-ingress/services
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
