---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.33
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/weaveworks/wego-app
      tag: v0.35.0

    envVars:
      - name: WEAVE_GITOPS_FEATURE_TENANCY
        value: "true"
      - name: WEAVE_GITOPS_FEATURE_CLUSTER
        value: "false"

    service:
      create: true
      type: ClusterIP
      port: 9001

    adminUser:
      create: true
      createSecret: false
      username: admin

    ingress:
      enabled: true
      className: int-ingress
      hosts:
        - host: &host "weave-gitops.${K8S_GATEWAY_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    networkPolicy:
      create: true

    metrics:
      enabled: false

    rbac:
      create: true
      impersonationResourceNames: ["admin"]
      additionalRules:
        - apiGroups: ["infra.contrib.fluxcd.io"]
          resources: ["terraforms"]
          verbs: ["get", "list", "patch"]

    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        memory: 500Mi

  valuesFrom:
    - kind: Secret
      name: cluster-user-auth
      valuesKey: password
      targetPath: adminUser.passwordHash