---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
        type: statefulset

    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.7.0.7588

    env:
      TZ: "${TZ}"
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${LOCAL_DOMAIN}"
      RADARR__LOG_LEVEL: info
      RADARR__API_KEY: ${API_KEY_RADARR}
      RADARR__AUTHENTICATION_METHOD: None

    hostname: *app

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: int-ingress
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Radarr
          gethomepage.dev/group: Media Automation
          gethomepage.dev/icon: radarr
          gethomepage.dev/description: Movie automation tool
          gethomepage.dev/widget.type: radarr
          gethomepage.dev/widget.url: "http://radarr.media.${CLUSTER_DOMAIN}:7878"
          gethomepage.dev/widget.key: "${API_KEY_RADARR}"
          gethomepage.dev/widget.enableQueue: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${LOCAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn-media

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/
        mountPath: /data

    resources:
      requests:
        cpu: 100m
        memory: 250M
      limits:
        memory: 300M
