---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app miniflux
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: ghcr.io/miniflux/miniflux
      tag: 2.0.48
    env:
      BASE_URL: https://miniflux.${EXTERNAL_DOMAIN}
      CREATE_ADMIN: "1"
      DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: miniflux-pguser-miniflux
            key: uri
      DEBUG: "1"
      LOG_DATE_TIME: "1"
      RUN_MIGRATIONS: "1"
      METRICS_COLLECTOR: "1"
      METRICS_ALLOWED_NETWORKS: "10.42.0.0/16"
      POLLING_SCHEDULER: entry_frequency
      POLLING_FREQUENCY: "15"
      FETCH_YOUTUBE_WATCH_TIME: 1

    envFrom:
      - secretRef:
          name: miniflux-secrets

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Miniflux
          gethomepage.dev/group: Tools
          gethomepage.dev/icon: miniflux.png
          gethomepage.dev/description: RSS Feed Aggregator
          gethomepage.dev/widget.type: "miniflux"
          gethomepage.dev/widget.url: "http://miniflux.tools.${CLUSTER_DOMAIN}:8080"
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 350Mi
