apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-k3s-helm-errors
  namespace: flux-system
spec:
  summary: Flux Helm Error
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
