apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-k3s-kustomize-info
  namespace: flux-system
spec:
  summary: Flux Kustomize Info
  providerRef:
    name: notif-info-provider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
