---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-wizarr
  namespace: flux-system
spec:
  dependsOn:
    - name: media-wizarr-config
  path: ./kubernetes/apps/media/wizarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-wizarr-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/wizarr/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
