---
- hosts: linux
  become: true
  tasks:
    - block:
      - name: Ensure non-free and contrib repositories are in sources.list
        lineinfile:
          path: /etc/apt/sources.list
          regexp: '^deb http://deb.debian.org/debian/ bookworm main'
          line: 'deb http://deb.debian.org/debian/ bookworm main non-free-firmware contrib non-free'
        register: repo_updated

      - name: Update apt cache if repo updated
        ansible.builtin.apt:
          update_cache: true
        when: repo_updated.changed

      - name: Gather facts (get current kernel versions)
        setup:
          filter: ansible_kernel

      - name: Install required packages
        ansible.builtin.apt:
          name:
            - nvidia-driver
            - firmware-misc-nonfree
            - dkms
            - "linux-headers-{{ ansible_kernel }}"
          state: present
        register: packages_installed

      tags:
        - setup

    - block:
      - name: Blacklist nouveau driver
        lineinfile:
          path: /etc/modprobe.d/nvidia-blacklists-nouveau.conf
          line: 'blacklist nouveau'
          create: true

      - name: Run update-initramfs -u
        command:
          cmd: update-initramfs -u
        when: packages_installed.changed

      tags:
        - post_install

    - name: Install nvidia-container-toolkit
      when: "'docker_hosts' in group_names"
      block:
        - name: Add the NVIDIA Docker GPG key
          ansible.builtin.get_url:
            url: https://nvidia.github.io/nvidia-docker/gpgkey
            dest: /etc/apt/keyrings/nvidia-docker.key
            mode: '0644'

        - name: Add the NVIDIA Docker repository
          ansible.builtin.get_url:
            url: https://nvidia.github.io/nvidia-docker/debian11/nvidia-docker.list
            dest: /etc/apt/sources.list.d/nvidia-docker.list
            mode: '0644'

        - name: Ensure ARCH is set to the machine's architecture
          set_fact:
            ARCH: "{{ ansible_architecture }}"

        - name: Add NVIDIA Docker repo signing key
          ansible.builtin.lineinfile:
            path: /etc/apt/sources.list.d/nvidia-docker.list
            regexp: '^deb https://nvidia.github.io/(.*)'
            line: 'deb [signed-by=/etc/apt/keyrings/nvidia-docker.key] https://nvidia.github.io/\1'
            backrefs: true

        - name: Import Nvidia GPG key
          ansible.builtin.apt_key:
            url: "https://nvidia.github.io/nvidia-docker/gpgkey"
            state: present

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

        - name: Install the containerized packages
          ansible.builtin.apt:
            name: 
              - nvidia-container-toolkit
              - nvidia-container-runtime
              - nvidia-docker2
            state: present

        - name: Restart Docker service
          ansible.builtin.service:
            name: docker
            state: restarted

    - name: Notify reboot handler if changes were made
      meta: flush_handlers

  handlers:
    - name: Reboot the system
      ansible.builtin.reboot:
      listen: "reboot_system"
      when: packages_installed.changed or repo_updated.changed
