---
- hosts: guests
  become: true
  tasks:
    - block:
      - name: Ensure non-free and contrib repositories are in sources.list
        lineinfile:
          path: /etc/apt/sources.list
          regexp: '^deb http://deb.debian.org/debian/ bookworm main'
          line: 'deb http://deb.debian.org/debian/ bookworm main non-free-firmware contrib non-free'
        register: repo_updated

      - name: Update apt cache if repo updated
        ansible.builtin.apt:
          update_cache: yes
        when: repo_updated.changed

      - name: Gather facts (get current kernel versions)
        setup:
          filter: ansible_kernel

      - name: Install required packages
        ansible.builtin.apt:
          name:
            - nvidia-driver
            - firmware-misc-nonfree
            - dkms
            - "linux-headers-{{ ansible_kernel }}"
          state: present
        register: packages_installed

      tags:
        - setup

    - block:
      - name: Blacklist nouveau driver
        lineinfile:
          path: /etc/modprobe.d/nvidia-blacklists-nouveau.conf
          line: 'blacklist nouveau'
          create: yes

      - name: Run update-initramfs -u
        command:
          cmd: update-initramfs -u
        when: packages_installed.changed

      tags:
        - post_install

    - name: Notify reboot handler if changes were made
      meta: flush_handlers

  handlers:
    - name: Reboot the system
      ansible.builtin.reboot:
      listen: "reboot_system"
      when: packages_installed.changed or repo_updated.changed
