---
- name: Install the essentials on the target
  hosts: default
  become: true

  vars:
    ansible_user: "administrator"
    default_user: "chkpwd"
    packages: [vim,htop]

  tasks:
    - name: Install essential packages # noqa package-latest
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest

    - name: Allow sudo group to have passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create a login user
      ansible.builtin.user:
        name: "{{ default_user }}"
        password: '*'
        state: present

    - name: Copy the public SSH key
      ansible.posix.authorized_key:
        user: "{{ default_user }}"
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBK2VnKgOX7i1ISETheqjAO3/xo6D9n7QbWyfDAPsXwa main"
      become: true

    - name: Disable SSH password auth
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"

    - name: Include | logrotate
      ansible.builtin.include_role:
        name: arillso.logrotate
      vars:
        logrotate_global_config: false
        logrotate_applications:
          - name: custom_logging
            definitions:
              - logs:
                  - /var/log/syslog.log
                  - /var/log/messages
                options:
                  - daily
                  - size 20M
                  - missingok
                  - rotate 10
                  - compress
                  - delaycompress
                  - notifempty
                  - create 640 root adm
                  - sharedscripts
                  - sharedscripts

    - name: Remove default user
      ansible.builtin.user:
        name: administrator
        state: absent
        remove: true
        force: true # User still as an active process
