---
- name: Test dynamic playbooks
  hosts: localhost

  tasks:
    - name: Debugging Variables
      ansible.builtin.pip:
        name: ansible
        virtualenv: /home/hyoga/test
        virtualenv_command: "sudo -u hyoga /usr/bin/python3 -m venv"
      become: false
