---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lynx-mongodb
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: mongodb
      version: 13.18.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    volumeClaimTemplates:
      - name: config
        mountPath: /bitnami/mongodb
        accessMode: ReadWriteOnce
        size: 8Gi
        storageClass: longhorn-database
