---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app palworld-server
  namespace: game-servers
spec:
  interval: 15m
  chart:
    spec:
      chart: placeholder
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: placeholder
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    namespace: game-servers

    server:
      annotations:
        reloader.stakater.com/auto: "true"

      resources:
        requests:
          cpu: 500m
          memory: 8Gi
        limits:
          memory: 12Gi

      storage:
        external: false
        preventDelete: false
        size: 60Gi
        storageClassName: longhorn-game-servers

      image:
        name: thijsvanloef/palworld-server-docker
        tag: v0.10.0
        imagePullPolicy: IfNotPresent

      ports:
        - name: game
          containerPort: 8211
          protocol: UDP
        - name: query
          containerPort: 27015
          protocol: UDP
        - name: rcon
          containerPort: 25575
          protocol: UDP

      strategy: Recreate

      service:
        enabled: true
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${PALWORLD_LB_ADDRESS}
        type: LoadBalancer
        ports:
          - name: game
            port: 8211
            protocol: UDP
            targetPort: 8211
          - name: query
            port: 27015
            protocol: UDP
            targetPort: 27015
          - name: rcon
            port: 25575
            protocol: UDP
            targetPort: 25575

      config:
        puid: 1000
        pgid: 1000
        port: 8211
        query_port: 27015
        max_players: 16
        multithreading: true
        rcon:
          enable: false
          port: 25575
          password: ""
        community:
          enable: true
          password: ""
        server_name: "Chkpwd - Palworld 02"
        timezone: ${TZ}
        public_ip: ${PUBLIC_IP}
        public_port: 8211
        server_description: "Pokemon: Gotta catch em all!"
        update_on_boot: true
        world_parameters:
          DAYTIME_SPEEDRATE: "1.000000"
          NIGHTTIME_SPEEDRATE: "1.000000"
          EXP_RATE: "1.000000"
          PAL_CAPTURE_RATE: "1.000000"
          PAL_SPAWN_NUM_RATE: "1.000000"
          PAL_DAMAGE_RATE_ATTACK: "1.000000"
          PAL_DAMAGE_RATE_DEFENSE: "1.000000"
          PLAYER_DAMAGE_RATE_ATTACK: "1.000000"
          PLAYER_DAMAGE_RATE_DEFENSE: "1.000000"
          PLAYER_STOMACH_DECREASE_RATE: "1.000000"
          PLAYER_STAMINA_DECREASE_RATE: "1.000000"
          PLAYER_AUTO_HP_REGEN_RATE: "1.000000"
          PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP: "1.000000"
          PAL_STOMACH_DECREASE_RATE: "1.000000"
          PAL_STAMINA_DECREASE_RATE: "1.000000"
          PAL_AUTO_HP_REGEN_RATE: "1.000000"
          PAL_AUTO_HP_REGEN_RATE_IN_SLEEP: "1.000000"
          BUILD_OBJECT_DAMAGE_RATE: "1.000000"
          BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: "1.000000"
          COLLECTION_DROP_RATE: "1.000000"
          COLLECTION_OBJECT_HP_RATE: "1.000000"
          COLLECTION_OBJECT_RESPAWN_SPEED_RATE: "1.000000"
          ENEMY_DROP_ITEM_RATE: "1.000000"
          DEATH_PENALTY: "All"
          ENABLE_PLAYER_TO_PLAYER_DAMAGE: "False"
          ENABLE_FRIENDLY_FIRE: "False"
          ENABLE_INVADER_ENEMY: "True"
          ACTIVE_UNKO: "True"
          ENABLE_AIM_ASSIST_PAD: "True"
          ENABLE_AIM_ASSIST_KEYBOARD: "False"
          DROP_ITEM_MAX_NUM: "3000"
          DROP_ITEM_MAX_NUM_UNKO: "1000"
          BASE_CAMP_MAX_NUM: "128"
          BASE_CAMP_WORKER_MAXNUM: "15"
          DROP_ITEM_ALIVE_MAX_HOURS: "1.000000"
          AUTO_RESET_GUILD_NO_ONLINE_PLAYERS: "False"
          AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS: "72.000000"
          GUILD_PLAYER_MAX_NUM: "3"
          PAL_EGG_DEFAULT_HATCHING_TIME: "72.000000"
          WORK_SPEED_RATE: "1.000000"
          IS_MULTIPLAY: "False"
          IS_PVP: "False"
          CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: "False"
          ENABLE_NON_LOGIN_PENALTY: "True"
          ENABLE_FAST_TRAVEL: "True"
          IS_START_LOCATION_SELECT_BY_MAP: "True"
          EXIST_PLAYER_AFTER_LOGOUT: "False"
          ENABLE_DEFENSE_OTHER_GUILD_PLAYER: "False"
          COOP_PLAYER_MAX_NUM: "4"
          REGION: ""
          USEAUTH: "True"
          BAN_LIST_URL: "https://api.palworldgame.com/api/banlist.txt"
