---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: awx-operator
      version: 2.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: awx-chart
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    fullnameOverride: &app awx
    AWX:
      enabled: true
      name: *app
      spec:
        admin_user: admin
        admin_email: ${AWX_ADMIN_EMAIL}
        admin_password_secret: ${AWX_ADMIN_PASSWORD}
        ingress_type: ingress
        ingress_class_name: int-ingress
        hostname: &host "awx.${LOCAL_DOMAIN}"
        ingress_annotations: |
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: AWX
          gethomepage.dev/group: Tools
          gethomepage.dev/icon: awx
          gethomepage.dev/description: "Ansible Automation Platform"
          gethomepage.dev/href: "https://awx.${LOCAL_DOMAIN}"
        ingress_path: /
        ingress_path_type: Prefix
        ingress_tls_secret: *host
        # web_resource_requirements:
        #   requests:
        #     cpu: 250m
        #     memory: 2Gi
        #   limits:
        #     memory: 300Mi
        # task_resource_requirements:
        #   requests:
        #     cpu: 250m
        #     memory: 1Gi
        #   limits:
        #     memory: 2Gi
        # ee_resource_requirements:
        #   requests:
        #     cpu: 250m
        #     memory: 100Mi
        #   limits:
        #     memory: 1Gi
        # postgres_resource_requirements:
        #   requests:
        #     cpu: 100m
        #     memory: 1Gi
        #   limits:
        #     memory: 2Gi
        # postgres_storage_requirements:
        #   requests:
        #     storage: 2Gi
        #   limits:
        #     storage: 5Gi
        postgres_storage_class: longhorn-database
        ipv6_disabled: true # https://github.com/ansible/awx-operator/blob/devel/docs/user-guide/advanced-configuration/disable-ipv6.md
