---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools-immich
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/immich/multi-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools-immich-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/tools/immich/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
