---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unifi-controller
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 2Gi
              storageClass: longhorn-config
              globalMounts:
                - path: /unifi

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: &context 999
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: jacobalberty/unifi
              tag: v7.5.174
              pullPolicy: IfNotPresent
            env:
              RUNAS_UID0: "false"
              UNIFI_UID: "999"
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              JVM_INIT_HEAP_SIZE:
              JVM_MAX_HEAP_SIZE: "1024M"

            resources:
              requests:
                cpu: 100m
                memory: 500M
              limits:
                memory: 1000M

    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${UNIFI_LB_ADDRESS}
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8443
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          stun:
            port: 3478
            protocol: UDP

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        enabled: true
        className: int-ingress
        hosts:
          - host: &host "{{ .Release.Name }}.${K8S_GATEWAY_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
