---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authentik
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.8.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    ingress:
      enabled: true
      ingressClassName: ext-ingress
      annotations:
        external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
      hosts:
        - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    env:
      AUTHENTIK_POSTGRESQL__HOST:
        valueFrom:
          secretKeyRef:
            name: authentik-pguser-authentik
            key: host
      AUTHENTIK_POSTGRESQL__NAME:
        valueFrom:
          secretKeyRef:
            name: authentik-pguser-authentik
            key: dbname
      AUTHENTIK_POSTGRESQL__USER:
        valueFrom:
          secretKeyRef:
            name: authentik-pguser-authentik
            key: user
      AUTHENTIK_POSTGRESQL__PASSWORD:
        valueFrom:
          secretKeyRef:
            name: authentik-pguser-authentik
            key: password
      AUTHENTIK_POSTGRESQL__PORT:
        valueFrom:
          secretKeyRef:
            name: authentik-pguser-authentik
            key: port
    envFrom:
      secretRef:
      name: authentik-secrets

    authentik:
      error_reporting:
        enabled: true

      email:
        from: "authentik <ocid@chkpwd.com>"
        host: smtp.gmail.com
        port: 465
        use_ssl: false

    postgresql:
      enabled: false

    redis:
      enabled: true

    prometheus:
      serviceMonitor:
        create: true

    resources:
      server:
        requests:
          cpu: 200m
        limits:
          memory: 500Mi