apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:sqxUYexd6KvMdhwrUYpttEfDxeM6rZHSkVY=,iv:MOd562nMW20ha1YpbMJMKA8Gm0cXMLstpFAYIbPQd7I=,tag:elxmisI4qcsuMjiWXykBag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QnNsdnRDZG80aWRiYkNo
            ZjdGdXM1Q2Q0OUZGdkNpZW5LY3lQNGlFSlJZClFNMis4cWQxLzkyVGsyd0IwNmds
            V3R4d3k0WVZ4THk3UjF0dW9OVzBKYncKLS0tIEhsUlVieGF0bDJPeWVvVTVpeFhN
            RkNTSmsySVJTVFFpeVF3cmFGOGs3SG8KblcEDHpV8cG8oxAASMPBpMo/7czyXvfO
            RqJWI6cX7emN25w42Cw3WLdS+Ri6pM3exUpROCeVMlmXL9vAcfp+mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T02:09:19Z"
    mac: ENC[AES256_GCM,data:8IsM1h/AA/PltE4O2x5oWtKu1Y/OMkptLJfEECKXOg8cnHb7H5PY8+HKlRdWmXGkhBUnodN8imj2Hx/INOPJj4l8DD+4is3nmypln8eDpo76zTPaJZhi/HHpINNkGjg0y7McXaMglgqosob7CqQh1nWjy4m8S3vovvCB7/4WAAY=,iv:UTthwU+46fGVr3gbFDDBIjZP1rcQReh/yOxzbBUI6rc=,tag:5pukQBZByG29VwVhgldSgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
