apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: security
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:DlLUHbZ2CEUIQtYF1JBVBK02Vw9NPsa0FjJGr67nwQ2x6ApFGMoh9S+9HT/pvbtrBks=,iv:uK1HiB4zACtC7cnrXz5Dasmk2IZwdLACMpIJbhy/A3s=,tag:EHWSfcFlLffVCfG6BbFkMg==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:RUwLLLq98iUTalXwlyjT142eEtc5,iv:f4pJCeADExu72vRXw6NGAfs5WDDej/XfrH0xxkSGMME=,tag:hXYIIvO8vBp7u2UHkQIgkw==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:uHR24hHOqrrmDa/MfrVvvA==,iv:JSo1FRkFg801AbyYyWAzwrFtQPiBDrWPXVuwtoM7V0c=,tag:9yzAZ7kYCfR1OqByYRYcEg==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:uetbkdxpa6hOzUwGq06lMloPEurodFYKjlvQYyk8nbE+Zj3fQU8oV57y7lZgEqYN,iv:R8/zTQN3YF/+xu08FGKOdxMlkoNewiZTGWCtoDLfpOs=,tag:biKuOcOxNjKKNvi0r0GlhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUDJ3bzVGRlFJcjI5bmNi
            Wll0eFBsV3dTMjJWZkkzS0lleTk1bkRpMGg4CmJqUkIralBFNC9GRWZEQ1dnZUxl
            QnpWREZyeDNPM3lIbWhyQy9lUUVHOVEKLS0tIEZuNzJLTTFYelVrbkhkVkJXVXlP
            NUxGVGdCN1pjM1N6d1FQaFR4OG1MMkkKVDEfyk7ZdWeM25d+dPPs1feZ7Ywa5QwV
            5g+sbnz/2VsxXojIIrMp5u2wOp2rMu/1/+q9Dd6dGMn9U5CjNgbGXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T22:41:47Z"
    mac: ENC[AES256_GCM,data:YmSV14HwUQ+9rWszwmdAANI5v7H4iuPVjsyADDADYHMJ/hHeJuRt/4r/t/CbUoBCdg8If0Aeg3S1J0agISE2vmmsyTBT0ucLfLrKCN2CLEvRH+ycy1s8Y7SwHSFYxf6eecVD38KaqOwx1GERZzrta9THRSIKG28raAVNjtHwJ3M=,iv:3xN9Y7U9KeEU4afCmIXKDWFSOS4JqoHbBCGNZv4MZ2I=,tag:ZanoODmj/0rFgrTvcAVBxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
