---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-kubevirt-cr
  namespace: flux-system
spec:
  dependsOn:
  - name: core-kubevirt-operator
  path: ./kubernetes/core/management/kubevirt-system/cr
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-kubevirt-operator
  namespace: flux-system
spec:
  path: ./kubernetes/core/management/kubevirt-system/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
