---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: reloader
      app.kubernetes.io/instance: reloader