apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    username: ENC[AES256_GCM,data:wu2RUZI=,iv:XyEwrvrc1ZY2k/MxrUmAh64IQHoy7Fv7hWqHhabxN04=,tag:UXf9odrF4fve2IrhijLtGw==,type:str]
    password: ENC[AES256_GCM,data:t26YiwzuC2MGOsSKGt2V2xUTl2ObPuEzaHKxBi8eN8ph9rn/I60CrBFJzb1wBo50UIbhHCgOr0quxcoo,iv:IWI1+v0tmThB7BpP9Oaar2cHXc4E/h2kmzKESIsM0A0=,tag:JhalAOknNbIcQOlyF1SoBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYTEyNjdHTU5RQ0NnNVY4
            a3Z4TmFrblphR29kOWFnelVXNFZMM2E5T1dBCmN1a1o1a2xhSHBZOU1na1ZZb2k5
            Z3V3OTV0aHMwN0lqOTBtMEdqUGt2cWMKLS0tIFJlVmUvZVJ4dmVuWHpraDBrazdy
            V091QVJOZ0tXODdxYWp5THJ3Rllad1EKgb1sAIdPdU9OTLADkco4QMM/ZbzmCzCQ
            EHs0NGH/bzpSH3VO5OgrJsCRlWUl6JtUJApH0Yu2dy/ExmyTJl4Khg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T05:27:06Z"
    mac: ENC[AES256_GCM,data:vIHap4mHp+sCrHMfgs4GBvwRLQPT5shIGosJtNyIpqFuLcYoKMhKlSeA5e9NDGfG8FEHEMzTUGBTGRool6c50Lb4Bq7gBDGaDzKi8GcpxOBEmTNNrxYITwyV6OKR4qxVgL2xI0WtlHPyLxSEJxcthJp83dh/XlCJN/MIDZMHFuQ=,iv:Ja1FPuofQ7TSK6RQRzHdR6S4A5MF/SqJ+GOuYli155c=,tag:DSf9cy/42+oLX/IqccKqiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
