apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    username: ENC[AES256_GCM,data:T0tdh7k=,iv:BnOifta5MClC8yExEVxLb4vTzI1CkFht574s1M5M3hY=,tag:G9VZUinM45vTeSOdCBBYKQ==,type:str]
    password: ENC[AES256_GCM,data:/PsYVWhOoZHyMz10uMwbBoPf2EPdLRlyhvH1WoRU1qlCXd8xoZYA/kcpP+QIcByA67KQ2xIVB3gkZsBc,iv:6ThIo3xkkjydyDFVPeABIEKj+NFoyTaiEoOotdlrSZ4=,tag:q/B9mL89M4bnEFXjf0jmCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVWU0T3J4Q1V6U3dMbDlw
            VVRxVGNKN1AwczBDSW54R1JpV2NRcUhqSWhNCkZhU29BUXZmOEsrcFR6OS9SLzU1
            VVJqeVNCRUhpYkhsWXpsUVpsa25SMEkKLS0tICtvRysvWmJSeDQwcGhLOTlLMzlM
            amswaDNLTG5EemFBY1Aza0F4TkhLM1EKOg9ZMwNQrzJnALKYF6f22j/zJkFeDnML
            JBjUNA87sU95aSNuuNk+ejyy9weK2D9fW9wqRDO+UTbBSgQmVKFxNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T11:12:47Z"
    mac: ENC[AES256_GCM,data:oTfyeVNhZYrj7YIZH3VK2HWi7ccSu1GkgfIuUjQ8N8C6mz3ylrFSm5XRIYFjjXwYvqdNO8ziNO0SVZ0a1pPuaBGZJUWLT3dpTG+4b4UZFewkE7MzWgmWNWpI08wQNBm7HfYmvTDviNuOWA6mC8JLL1QH4Jcy/GYfxUUcvSQRtOY=,iv:V79RH1UYjagFDdDD3qqtO6vhio0JO+i6TRBiADoNp3Y=,tag:K3rOkPxkXxSMwngoFV3ovA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
