USR_PASSWORD_SOPS: bryanswag12
CF_EMAIL: unix.chkpwd@gmail.com
SWAG_CF_API_TOKEN: ZrebAIHCxnlEpkqEuml-41D-V-5Oxu27E57UlrUX
DISCORD_TOKEN: https://discord.com/api/webhooks/1042233604710875306/8Ev5a2_Dc_7CYHDIr1C6FFRAeJBSM1J2t4PQcgJng81OcDAWPiW4Dmd6NgX2o2NUynSn
PLEX_TOKEN: 4ax9LnhZNz4fAfCHJYyG
COUCHDB_DB_PASSWORD: Overhang-Repeater9-Alkaline
GMAIL_ADDR: unix.chkpwd@gmail.com
GIST_ID: a05f7532ac464c2ec6fe433333b55f6a
GIST_TOKEN: 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
AGE_KEY_SECRET_BASE64:
DROPBOX_MEDIA_CLIENT_ID: xqobwzouq2y7myg
DROPBOX_MEDIA_CLIENT_SECRET: srit2guj6xnp61b
CRYPT_PASS1: zOb_OWHEhplQe3sqjPzBDyrjqEqfa90uM5gyjEuyVGjo_V3xNRN4p6J_8ul3CbtenkJ0WpoC7jGLADd-xzFeH2Pu63X_6DB8Yr0klJ8Z6lDkg8AQez0TtlU0AuoKjZl-bj5a-Ke_bPVM7pNsirT7B4aURTvLsxVHlkm0bwSkGb
CRYPT_PASS2: GvTY4kVMugVoqkvsqX_OzhDagnslg_v5T0Sy46U-fwtOGeCy4NalmJuCm3ubocxi6_B2cOVG7UmhEyyYEqRPzGhDDVXgXHS9vwtpYePYYupYbr3i_wxHKCLtz_7qX76RaTrkblUARmXM-HE35_ca8Mrx_SQtWv0XKNMEqbyk_wQ
DROPBOX_IMAGES_CLIENT_ID: rmxrz7jfp959813
DROPBOX_IMAGES_CLIENT_SECRET: 7iehfkqp58gv66g
DISCORD_PLEX_BACKUP_WEBHOOK: https://discord.com/api/webhooks/1042233604710875306/8Ev5a2_Dc_7CYHDIr1C6FFRAeJBSM1J2t4PQcgJng81OcDAWPiW4Dmd6NgX2o2NUynSn
DISCORD_UPTIME_KUMA_WEBHOOK: https://discord.com/api/webhooks/1135679598793871513/n8FjZ4-VYp2VgK8SgtxRIK7nyxpANOjf4QT79cA_d74vsbK76y0MeTCdWTNN09NfvbLy
UPTIME_KUMA_PASSWORD: Urologist-Preshow-Foe9