---
apiVersion: v1
kind: Service
metadata:
  name: opnsense
  namespace: ingress-nginx-system
spec:
  type: ExternalName
  externalName: 172.16.16.1
  ports:
    - name: http
      port: &port 80
      protocol: TCP
      targetPort: *port
