---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-server
  namespace: tools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  dependsOn:
    - name: immich-typesense
      namespace: tools
    - name: immich-redis
      namespace: tools

  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: immich-secret

    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.74.0
    args: ["start-server.sh"]
    command: /bin/sh
    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-cm

    service:
      main:
        ports:
          http:
            port: 3001

    persistence:
      library:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/images
        mountPath: /usr/src/app/upload

    resources:
      requests:
        cpu: 100m
        memory: 250Mi
