---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zipline
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    image:
      repository: ghcr.io/diced/zipline
      tag: 3.7.4

    env:
      TZ: "${TZ}"
      CORE_SECRET:
        valueFrom:
          secretKeyRef:
            name: zipline-secrets
            key: CORE_SECRET
      CORE_DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: zipline-secrets
            key: CORE_DATABASE_URL
      CORE_HOST: "0.0.0.0"
      CORE_RETURN_HTTPS: "true"
      CORE_PORT: "3000"
      CORE_LOGGER: "true"
      WEBSITE_TITLE: "File Server"
      UPLOADER_DEFAULT_FORMAT: "NAME"
      MFA_TOTP_ENABLED: "true"

    hostname: *app

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/misc
        mountPath: /zipline/uploads

    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        memory: 300Mi
