---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app linkwarden
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /data/data
              accessMode: "ReadWriteOnce"
              size: 2Gi
              storageClass: longhorn-config

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: &context 65532
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: main
            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-pguser-linkwarden
                    key: uri
              NEXTAUTH_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-secrets
                    key: nextauth-secret
              NEXTAUTH_URL: "https://linkwarden.${EXTERNAL_DOMAIN}"
              NEXT_PUBLIC_DISABLE_REGISTRATION: "true"

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: false

    resources:
      requests:
        cpu: 13m
        memory: 64Mi
      limits:
        memory: 256Mi
