---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system

  values:
    controller:
      replicaCount: 1
      updateStrategy:
        type: RollingUpdate # * Spins up a new pod before the old pod
        rollingUpdate:
          maxSurge: 1
      extraArgs:
        default-ssl-certificate: cert-manager/chkpwd-cert # * The tls secret name for every CR. This will allow every ingress resource to use the default.

      service:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 172.16.16.204
        externalTrafficPolicy: Cluster # * With 'Local' set - Finds the source of the response and stops hopping afterwards
      publishService:
        enabled: true # * If not set, it will report back the status and what IP address
      ingressClassResource:
        default: true

      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        enable-brotli: "true" # * Compression Algorithym
        enable-real-ip: "true"
        # forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: 0
        proxy-buffer-size: "16k"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
