---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: immich
  namespace: tools
spec:
  image: ghcr.io/chkpwd/cdpgvecto.rs:main@sha256:acbec4ab9750d44bcb042b1eee04e856bfac254823f2a02ae72bff034627d2ed
  postgresVersion: 15

  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        pg_hba:
          - hostnossl all all 10.42.0.0/16 md5
          - hostssl all all 0.0.0.0/0 md5
        parameters:
          shared_preload_libraries: vector

  instances:
    - dataVolumeClaimSpec:
        storageClassName: longhorn-database
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

  users:
    - name: immich
      databases:
        - immich
      options: "SUPERUSER"

  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: longhorn-database
              accessModes:
              - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
