---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
spec:
  storageClassName: longhorn-media
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: "cockpit.${LOCAL_DOMAIN}"
    path: /mnt/data/images
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: tools
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-media
  resources:
    requests:
      storage: 1Mi
