apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
stringData:
  address: https://discord.com/api/webhooks/1142138214056988685/XOL-SomsuDOPg3PGe0qS0MrxXjK5Pn0eOuCongDWlqgwzILh_qAbtr9-KtG8uFNv7GfB/slack
