apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.5.1
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      host: longhorn.${LOCAL_DOMAIN}
      tls: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Longhorn
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: longhorn.png
        gethomepage.dev/description: Storage Manager
        gethomepage.dev/href: "http://{{ .Release.Name }}.${LOCAL_DOMAIN}"

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Retain
      recurringJobSelector:
        enable: false

    monitoring:
      enabled: true
      createPrometheusRules: true

    defaultSettings:
      defaultReplicaCount: 3
      backupTarget: nfs://cockpit.${LOCAL_DOMAIN}:/mnt/data/backup/longhorn
      backupstorePollInterval: 60
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultDataPath: /mnt/data/longhorn
      defaultDataLocality: best-effort
      defaultLonghornStaticStorageClass: longhorn
      storageMinimalAvailablePercentage: 0
      storageReservedPercentageForDefaultDisk: 0
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      restoreVolumeRecurringJobs: true
