apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: blog-site-runner
  namespace: continuous-integration
spec:
  replicas: 1
  template:
    spec:
      repository: chkpwd/blog-chkpwd
