apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: packer-build-runner
  namespace: continuous-integration
spec:
  replicas: 1
  template:
    spec:
      repository: chkpwd/iac
      env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
