---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: game-servers-palworld-server
  namespace: flux-system
spec:
  dependsOn:
    - name: game-servers-palworld-server-config
  path: ./kubernetes/apps/game-servers/palworld-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: game-servers-palworld-server-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/game-servers/palworld-server/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
