---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-server
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-game-servers
  resources:
    requests:
      storage: 60Gi
