apiVersion: v1
kind: Secret
metadata:
    name: palworld-server-secrets
    namespace: game-servers
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:2ZHekuHPyoBSn7q2feRvN+Fd,iv:kNPxFN/k2Lr0FwpufIxYB0BjIPh6qjVmkKF3HKb0sM8=,tag:drPhESO9aKiMraK50WaSVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NGtGam9qZ1BRdXVaelRE
            eFF3MzdXYUFzNEMySGg0a0JFS3JGK3lxckdJCmliNlBtbDhkQUlJZHcwb0xyUVJo
            L3pYcElYcDhNODlpeTdRT3hsVFQ0S1kKLS0tIHlRcWxZVFByWm0yampiR1d4ZlVM
            QStERFB1YklWZVp5N3J0R0s4bitUTVEKJqCTusacSMyKlmCh3EqTdXN+pOH/qQeV
            1bRD33v7GfgmYxA7132xKKwnKx/rjjw+MC1/aBVvySOJjcp1dWKaRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T16:20:39Z"
    mac: ENC[AES256_GCM,data:IEoauNQzeMLHeGHlWrCEEyj0wWoWKTu6MI8Kg0lG1zPacoMSDkGcslTnVCUBsovykDGv0iyHpkX2fU8tNz0BQn0Mot8V3WmKDqTE6/YkQoz5/q4SabWte4r8WZg/kyYGBL7FcoxQELV3nsKkUDxOgz1mB9f49/eXy4uqkKp7OpI=,iv:W44+1Efxi701ta0Qiic5D4OYnGGXcV9h4YNvEGMbAOc=,tag:yG2+j6LDzy1cTGU1iyVMAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
