apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app palworld-server
  namespace: game-servers
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: *app
  serviceName: *app
  replicas: 1
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - name: *app
          image: thijsvanloef/palworld-server-docker:v0.10.0
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: PORT
              value: "8211"
            - name: PLAYERS
              value: "16"
            - name: MULTITHREADING
              value: "false"
            - name: RCON_ENABLED
              value: "false"
            - name: RCON_PORT
              value: "25575"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: palworld-server-secrets
                  key: ADMIN_PASSWORD
            - name: COMMUNITY
              value: "false"
            - name: UPDATE_ON_BOOT
              value: "true"
          ports:
            - containerPort: 8211
              protocol: UDP
              name: server
            - containerPort: 27015
              protocol: UDP
              name: query
            - containerPort: 25575
              protocol: TCP
              name: rcon
          volumeMounts:
            - name: data
              subPath: palworld
              mountPath: /palworld
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              memory: 6Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: palworld-server
