---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools-esxi-config-backup
  namespace: flux-system
spec:
  dependsOn:
    - name: tools-esxi-config-backup-config
  path: ./kubernetes/apps/tools/esxi-config-backup/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools-esxi-config-backup-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/tools/esxi-config-backup/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
