---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esxi-backup-config
  namespace: tools
data:
  config.yml: |
    esxi_hosts:
      - hostname: octane.local.chkpwd.com
        username: root
        password: ${ESXI_HOST1_PWD}
