---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app youtubedl-material
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controllers:
      main:
        enabled: true
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        pod:
          enableServiceLinks: false
          securityContext:
            runAsNonRoot: true
            runAsUser: &context 2310
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"
            seccompProfile:
              type: RuntimeDefault

        containers:
          main:
            image:
              repository: tzahi12345/youtubedl-material
              tag: 4.3.2
              pullPolicy: IfNotPresent

            env:
              TZ: "${TZ}"
              UID: *context
              GID: *context
              ytdl_auth_method: "internal"
              ALLOW_CONFIG_MUTATIONS: "true"
              ytdl_use_local_db: "true"
              write_ytdl_config: "true"
              ytdl_logger_level: verbose
              ytdl_use_api_key: "true" # API toggle
              ytdl_api_key:
                valueFrom:
                  secretKeyRef:
                    name: youtubedl-material-secrets
                    key: YOUTUBEDL_API_KEY
              ytdl_url: "https://ytdl.${EXTERNAL_DOMAIN}"
              ytdl_title_top: YoutubeDL
              ytdl_default_theme: dark
              ytdl_file_manager_enabled: "true"
              ytdl_enable_downloads_manager: "true"
              ytdl_allow_quality_select: "true"
              ytdl_custom_args: "\
                --write-sub,,\
                --sub-lang,,en.*,,\
                --add-metadata,,\
                --embed-thumbnail,,\
                --embed-subs,,\
                --convert-thumbnails,,png,,\
                --convert-subs,,srt,,\
                --sponsorblock-mark,,sponsor,intro,outro,selfpromo,preview,interaction,poi_highlight,chapter"
              ytdl_default_file_output: "YouTube/%(uploader)s [%(uploader_id)s]/%(title)s [%(id)s]"
              ytdl_video_folder_path: media
              ytdl_subscriptions_base_path: media/YouTube
              ytdl_allow_subscriptions: "true"
              ytdl_subscriptions_check_interval: "900"
              ytdl_subscriptions_redownload_fresh_uploads: "true"
              ytdl_include_thumbnail: "true"
              ytdl_include_metadata: "true"
              ytdl_max_concurrent_downloads: "5"
              ytdl_use_youtube_api: "false"
              ytdl_use_sponsorblock_api: "true"
              ydtl_default_downloader: yt-dlp
              ytdl_use_default_downloading_agent: "true"
              ytdl_allow_advanced_download: "true"
              ytdl_use_cookies: "false"
            
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

            resources:
              requests:
                cpu: 10m
                memory: 150Mi
              limits:
                memory: 1000Mi

    service:
      main:
        ports:
          http:
            port: 17442

    ingress:
      main:
        enabled: true
        className: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "ytdl.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: longhorn-media
        size: 100Mi
        advancedMounts:
          main:
            main:
              - path: /app/appdata
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/downloads/youtube
        advancedMounts:
          main:
            main:
              - path: /app/media/YouTube
