---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
namespace: development
configMapGenerator:
  - name: awx-extra-configs
    files:
      - ansible.cfg=./ansible.cfg
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled