---
buckets:
  - extras
  - main
  - versions
  - games
chocolates:
# Drivers
  - amd-ryzen-chipset
  - geforce-game-ready-driver
  - hwinfo
  - dropbox
scoops:
# Drivers
  - nvcleanstall
# Games
  - sunshine
  - ryujinx
  - versions/steam
  - epic-games-launcher
  - playnite
# Development
  - k9s
  - git
  - neovim
  - vscode
  - hugo
  - rclone
  - openlens
  - starship
  - chezmoi
  - podman-desktop
  - bitwarden-cli
  - powershell-core
# Tools
  - 7zip
  - sharex
  - postman
  - powertoys
# Communication
  - whatsapp
  - discord
  - zoom
# Utilities
  - bitwarden
  - authy
  - vlc
  - obsidian
  - plex-desktop
  - prusaslicer
  - firefox
