---
- name: Bootstrap Process
  ansible.builtin.include_tasks: bootstrap.yaml

- name: Change the hostname to loba
  ansible.windows.win_hostname:
    name: chk-dev-win11
  register: hostname

- name: Install dependencies
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ chocolates }}"
    state: present

- name: Registry Edits
  ansible.builtin.include_tasks: registry.yaml

- name: Define Taskbar Layout
  ansible.windows.win_powershell:
    script: |
      Import-StartLayout -LayoutPath "TaskbarLayout.xml" -MountPath "{{ ansible_facts.env.TEMP }}\templates\TaskbarLayout.xml"

- name: Install Windows Features
  ansible.windows.win_optional_feature:
    name: 
      - Microsoft-Windows-Subsystem-Linux
      - ServicesForNFS-ClientOnly
      - ClientForNFS-Infrastructure
    state: present
  notify: Reboot if feature requires it

- name: Change power plan to Balanced
  community.windows.win_power_plan:
    name: balanced

- name: Ensure RDP rights are given to {{ ansible_user }}
  ansible.builtin.include_tasks: users.yaml

- name: Update the system
  ansible.builtin.include_tasks: system.yaml
