---
- name: Restart ssh daemon
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
  when: ansible_host != 'localhost'

- name: Restart code-server
  ansible.builtin.service:
    name: code-server@{{ common_user }}.service
    state: restarted
  become: true
  when: ansible_host != 'localhost'
