---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app pyload
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    controller:
      type: statefulset

    image:
      repository: lscr.io/linuxserver/pyload-ng
      tag: 0.5.0

    env:
      TZ: ${TZ}
      PUID: &context 1000
      PGID: *context

    hostname: *app

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        ingressClassName: ext-ingress
        annotations:
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: &context 1000
      runAsGroup: *context
      fsGroup: *context
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn-media

    persistence:
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/downloads/pyload
        mountPath: /data

    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 200Mi
