---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: core-cert-manager-config
  path: ./kubernetes/core/networking/cert-manager-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager-config
  namespace: flux-system
spec:
  path: ./kubernetes/core/networking/cert-manager-system/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: core-cert-manager
  path: ./kubernetes/core/networking/cert-manager-system/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: core-cert-manager
  path: ./kubernetes/core/networking/cert-manager-system/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
