name: docker-build-workstation

on:
  push:
    branches: [ main ]
    paths: [ docker/dev/** ]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current timestamp
        id: time
        run: echo "time=$(date +'%s')" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: docker/dev/
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: |
            ghcr.io/chkpwd/dev:latest-${{ matrix.platform }}
            ghcr.io/chkpwd/dev:auto-${{ steps.time.outputs.time }}-${{ matrix.platform }}
          push: ${{ github.ref == 'refs/heads/main' }}