name: Docker Build Dev Container

on:
  push:
    branches: [ main ]
    paths: [ docker/dev/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current timestamp
        id: time
        run: echo "time=$(date +'%s')" >> $GITHUB_OUTPUT

      - name: Build and push images
        uses: docker/build-push-action@v5.0.0
        with:
          context: docker/dev/
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/chkpwd/dev:latest
            ghcr.io/chkpwd/dev:auto-${{ steps.time.outputs.time }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
