---
- name: Install nfs package
  ansible.builtin.apt:
    pkg: 'nfs-common'

- name: Create the dest directory for the mount
  ansible.builtin.file:
    path: "{{ media_path }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: '0755'

- name: Mount NFS share from TrueNAS
  ansible.posix.mount:
    src: "cockpit:/mnt/data"
    path: "{{ media_path }}"
    opts: rw,sync,hard,nofail
    state: mounted
    fstype: nfs

- name: Configure Pigz Backup for Plex
  ansible.builtin.include_tasks: setup_backup.yaml
